### ISSUE TITLE
About the source code of the libtf.cc/libtf.c

### ISSUE THREAD

**Issue by CristXu** [openmv/openmv#1025]
Hi, 
     I found that there is only a libtf.a under the libtf folder, i want to check if the source code is available for the pubilc,
Because i want to use another toochain to build the openmv, and it seems that the .a is not compatible. if so, where 
can i find these sources code if this is possiable? such as the libtf.c? 

Regards

**Comment by kwagyeman** [comment]
It’s in another repo. The openmv/TensorFlow lib repo.

Um, just to note, you are signing up for a devastating amount of work to compile that code with another tool chain. The reason we make it into a .a file is because it was very hard to integrate.
