### ISSUE TITLE
V3.8.0 The LED CAN NOT work

### ISSUE THREAD

**Issue by jiskra** [openmv/openmv#1028]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Describe your setup

**IDE version:**

**Firmware version:**

**Operating system:**

### For developers

**GCC version:**

**Build target:**

**Comment by kwagyeman** [comment]
And? What is wrong?

**Comment by iabdalkader** [comment]
@jiskra please fill the issue template.
