### ISSUE TITLE
Incorrect parameter name pixel_threshold in documentation

### ISSUE THREAD

**Issue by sebromero** [openmv/openmv#1038]
**Describe the bug**
In the docs it says that one can use `pixel_threshold` as a paramter for `find_blobs` while it should be `pixels_threshold`.

**To Reproduce**
1. Go to https://docs.openmv.io/library/omv.image.html?highlight=find_blobs#image.image.Image.image.find_blobs
2. See the incorrect information

**Expected behavior**
The parameter name should be `pixels_threshold`.

**Screenshots**
![image](https://user-images.githubusercontent.com/1326220/102627406-72898d00-4148-11eb-9f27-494fa9d6369f.png)

**Comment by kwagyeman** [comment]
https://github.com/openmv/micropython/pull/86
