### ISSUE TITLE
change SPI LCD to 1.44 inches

### ISSUE THREAD

**Issue by HarryZeng** [openmv/openmv#1069]
Hello, I want to change the 1.8 inch SPI LCD screen to a 1.44 inch SPI LCD screen；(1.44 inch screen resolution is  128x128)
However, I modified the configuration parameters in py_lcd_init(py_lcd.c line:1296)  change 160 to 128.
But it doesn't work, Garbled screen

May I ask what else needs to be modified?

SPI LCD Driver is ST7735S
And I checked the connection between SPI LCD and OpenMV4 is correct

**Comment by kwagyeman** [comment]
Hi, it may need more regs to be set. Please try this customers code:

https://forums.openmv.io/viewtopic.php?f=6&t=2189#p13167
