### ISSUE TITLE
WiFi shield pins silkscreen labels are wrong for last 3 generation of products

### ISSUE THREAD

**Issue by frank26080115** [openmv/openmv#1145]
The top right 4 pins of the WiFi shield are NC but pass through signals from the parent OpenMV. They are labelled RST, BOOT, SWD, and SWC.

However, on the actual OpenMV H7 Plus, H7, and M7, that label is wrong! The signals are actually P9, SYNC, BOOT, RST

**Comment by kwagyeman** [comment]
This is a won't fix. Oh, so, we are going to rev the product line this year. We've got a lot of new drivers that are all better now and we are planning on making better stuff.
