### ISSUE TITLE
JPEG decode error (cannot decode image data)

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#116]
hello,I made an openmv1 board, and use ov2640, but when I run helloworld.py in ide, the terminal always print "JPEG decode error (cannot decode image data)".

could you help me?

**Comment by iabdalkader** [comment]
I'm not doing much work on OpenMV 1 right now since it was never released.

**Comment by kidswong999** [comment]
so, OpenMV 1 will not update?  it's so tiny, and i want to add it to my mini quadrotor. 
And I want to join the project, is there any group?

**Comment by iabdalkader** [comment]
I will get around to it, but OpenMV-2 has higher priority right now

**Comment by kidswong999** [comment]
I think the error is, my ov2640 module is not the same as yours. so...could you send me your cam module infomation? Because of my skill level, I rewrite the driver is TOO difucult...
thanks!

**Comment by kidswong999** [comment]
I save RGB565 image into SD card, but the image is mess up.
like this
![Uploading rgb565.png…]()

could you help me about this?

**Comment by kwagyeman** [comment]
Closing old stuff.
