### ISSUE TITLE
Compile error: LED_IR and DCMI_FSIN_PIN not define for OPENMV1

### ISSUE THREAD

**Issue by x893** [openmv/openmv#117]
Hi,
i use OpenMV1 and try compile. But LED_IR and DCMI_FSIN_PIN not defined.
Also sdcard_spi.c not compile (no pincfg.h) and may be other.
Can you check compilation for OpenMV1 version ?

Best regards
Mitek

**Comment by iabdalkader** [comment]
Hi, OMV2 has a higher priority right now, I'll get around to fixing OMV1 soon.

**Comment by x893** [comment]
Hi,
OK, i'll wait or make changes myself.
Thanks for your project !
