### ISSUE TITLE
uselect poll in wifi module

### ISSUE THREAD

**Issue by Just1045523143** [openmv/openmv#1230]
Environment:
IDE:2.6.9
Firmware version:3.9.3

Problem:
i wanna use wifi module to communicate with other device, receive data from wifi and send the raw data by uart to other micro-controller. As you know, when wifi receiving data, it is blocked, so i use uselect::poll function, but, when runing poll() function, some error:OSError [Error 5]EIO occur. Someone can save me?
This is my code:
`
client = usocket.socket(usocket.AF_INET, usocket.SOCK_STREAM)
client.bind((host,port))
client.listen(1)

while True:
    c,addr=client.accept()
    #c.settimeout(0.1)
    #c.setblocking(False)
    poller = uselect.poll()
    poller.register(c, uselect.POLLIN | uselect.POLLHUP)
    while True:
        res, event = poller.ipoll(1000)  # *****OSError [Error 5]EIO*****

        if not res:
            break
        else:
            uart.write(data.decode())
        if uart.any():
            a = uart.readline().decode()
            c.send(a.encode())
        else:
            print('uart no data')
    client.close()`

**Comment by kwagyeman** [comment]
Please repost on the forums: https://forums.openmv.io/
