### ISSUE TITLE
FSIN pin isn't used?

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#124]
I found that in the schematic of OPENMV2 with OV7725, the FSIN pin is conneted to PD3 in STM32F427.
But I didn't find any FSIN in the project source code.
Is the FSIN pin not used?

Thanks!

**Comment by iabdalkader** [comment]
It's configured but not used, I tried it once to sync the frame capture, works really well, except it messes up the auto-functions. The OV7725's framerate is fast enough so we don't actually needed right now.
