### ISSUE TITLE
OPENMV1 with FPC CAM

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#127]
![openmv2fpc](https://cloud.githubusercontent.com/assets/9582040/14749511/67ce1a90-08f2-11e6-9fdc-49e105ef89f1.png)

Because of the weight and for using long FPC.
I replaced BGA IC CAM to FPC CAM, but some details haven't done. 

Can it work?

**Comment by iabdalkader** [comment]
Sure, I don't see why not.

**Comment by kidswong999** [comment]
![image](https://cloud.githubusercontent.com/assets/9582040/14758918/2c97a8a6-0942-11e6-9cdb-776c394dd874.png)

OK, I will make one these days, Thank you!

**Comment by kidswong999** [comment]
![image](https://cloud.githubusercontent.com/assets/9582040/14758918/2c97a8a6-0942-11e6-9cdb-776c394dd874.png)

OK, I will make one these days, Thank you!

**Comment by kwagyeman** [comment]
Please remove our logo information from any custom designs.

Thanks,
