### ISSUE TITLE
RGB888 Support in image_bpp?

### ISSUE THREAD

**Issue by glegrain** [openmv/openmv#1282]
Hi,

I would like to create `image_t` objects with RGB888 pixel format (24-bit per pixel) but IMAGE_BPP_RGB888 is not part of the `image_bpp_t` enum. If I understand correctly, any bpp value > 3 is considered as JPEG data and represents the JPG size.

How can we add support to RGB888 pixel format to `image_t` objects?

https://github.com/openmv/openmv/blob/24584bdc9c2684234b51ec56907aec2428c34113/src/omv/imlib/imlib.h#L343-L351

**Comment by kwagyeman** [comment]
You just need to insert the format before IMAGE_BPP_JPEG.

Not all our code uses these enums though... so, beware.

...

I have plans to add support for ARGB8888 and YUV422 later this year. I can't say when. But, I have no plans of making RGB888 a long term option. It's very inefficient. The 3-byte offset removes the possibly of doing a lot of tricks.
