### ISSUE TITLE
Servo class don't work in firmware 4.0.0

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#1325]
**Describe the bug**
When updated to 4.0.0, the Servo class cannot drive the servo, and the oscilloscope has no waveform.
It should be a fault caused by micropython. The Timer class is works.

bad code:
```
import time
from pyb import Servo

s1 = Servo(1) # P7
s2 = Servo(2) # P8
s3 = Servo(3) # P9

while(True):
    for i in range(1000):
        s1.pulse_width(1000 + i)
        s2.pulse_width(1999 - i)
        s3.pulse_width(1000 + i)
        time.sleep_ms(10)
    for i in range(1000):
        s1.pulse_width(1999 - i)
        s2.pulse_width(1000 + i)
        s3.pulse_width(1999 - i)
        time.sleep_ms(10)
```

good code:
```
from pyb import Pin, Timer

p = Pin('P7')
tim = Timer(4, freq=50)
ch = tim.channel(1, Timer.PWM, pin=p)
ch.pulse_width_percent(50)

while True:
    pass

```

 - IDE version: [2.6.9]
 - Firmware version: [4.0.0]
 - Board: [OPENMV-H7]
 - OS: [Windows]

**Comment by iabdalkader** [comment]
Could this be related ? https://github.com/openmv/openmv/commit/daa99135bc6da54d17f50f37ae986825ba30f21b @kwagyeman

**Comment by kidswong999** [comment]
This bug has not been completely resolved. When the IDE is disconnected and connected again, it will no longer work.

**Comment by kidswong999** [comment]
I used the OpenMV4 H7 Plus board. firmware 4.0.1.

The servo is working for the first time after power on. But running it again will not work.

code:
```
import time
from pyb import Servo

s1 = Servo(1) # P7
s2 = Servo(2) # P8

s1.pulse_width(1000)
s2.pulse_width(1000)

while(True):
    pass
```

**Comment by kidswong999** [comment]
It should be a failure to reinitialize the servo. 
The following code will not generate pwm.
```
import time
from pyb import Servo

s1 = Servo(1) # P7
s1.pulse_width(1000)

s1 = Servo(1) # P7
s1.pulse_width(2000)

while(True):
    pass
```

**Comment by iabdalkader** [comment]
Okay will test it.

**Comment by kidswong999** [comment]
Hi, I tested in version 4.4.2 and Servo still has issues. Can you check it?
