### ISSUE TITLE
openmv2 Failed to init sensor, error:-2

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#134]
everything is OK, except the sensor.
OpenMV2 failed to init sensor, error:-2.
I search the source code, maybe can not probe sensor.

thanks.

**Comment by Iamttp** [comment]
my openmv4 produced the same problem "FATAL ERROR: Failed to init sensor, error:-2".
Can you tell me how to solve it in the end? Should I replace a new camera?

**Comment by kwagyeman** [comment]
The OMV2 is a rather old system. Where I'd dyou buy it from.

**Comment by Iamttp** [comment]
Hi, Can you tell me what should i do when my openmv4 produced the problem "FATAL ERROR: Failed to init sensor, error:-2"?

**Comment by Iamttp** [comment]
Is it necessary to replace the camera?

**Comment by kwagyeman** [comment]
Um, so, if you look at the source code sensor.c you can see what throws that error.

Um, generally, that means the hardy has issues. I'm not in a place to be able to answer this question in more detail right now.

**Comment by iabdalkader** [comment]
It generally means the sensor is not responding to I2C scans. Did you remove/replace the sensor ?

**Comment by Iamttp** [comment]
no, I have been using it all the time. The camera was still good before

**Comment by Iamttp** [comment]
The last time I used it was to use the dupont line give openmv five volts. and the LED kept shining and i found a error log file.

**Comment by iabdalkader** [comment]
dupont line ?

**Comment by Iamttp** [comment]
I am so sorry to my English. It just powers openmv.

**Comment by iabdalkader** [comment]
Anyway, this is not a software issue, it sounds like the camera has been damaged and you'll need a replacement.

**Comment by Iamttp** [comment]
OK, thank you
