### ISSUE TITLE
Reset I/O pin states and LED states

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv#135]
The firmware should default all I/O pin states to their default power on values after a soft reset. Additionally, the issue with the red LED turning on randomly needs to be fixed.

**Comment by iabdalkader** [comment]
Going to close this outdated issue (for the record, some pins are configured once, can't reset them on soft resets). It's probably worth mentioning too that the red LED turns on when cache is being flushed. Note I'll try to add LittleFS support as a second Filesystem option for the next release. I think LittleFS can be mounted on Linux (from userspace), at least the files will be accessible from Linux.
