### ISSUE TITLE
set_windowing not work at some parameter

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#1350]
When it is a certain parameter, set_windowing will fail, causing an error:

RuntimeError: Capture Failed: -2
I used OpenMV4 Plus, firmware 4.0.1.

code:
```
import sensor, image, time

sensor.reset()
sensor.set_pixformat(sensor.GRAYSCALE)
sensor.set_framesize(sensor.VGA)
sensor.set_windowing((230, 45, 94, 85))
sensor.skip_frames(time = 1000)

while(True):
    img = sensor.snapshot()
```

**Comment by kwagyeman** [comment]
This will happen if you ask for an image that’s not a multiple of 16 bytes. This is not an error. However, I think I should add better error messages. Anyway, the resolution you are asking for is not possible to capture.
