### ISSUE TITLE
Hardware: Use through-hole Micro-USB Connector

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv#136]
For new OpenMV Cams the micro-USB connector needs to use a through-hole variant to make it more robust. I realize that a through-hole connector will require the servo headers on the back of the board to be dropped. This is fine. Those connectors prevent MacroFab from using a selective solder machine easily which increases the cost of building the boards: https://www.youtube.com/watch?v=p-VImd2yW5s

**Comment by kwagyeman** [comment]
See the connector the pyboard uses: https://github.com/micropython/pyboard/tree/master/eagle

**Comment by anedel** [comment]
@kwagyeman: You wrote "a through-hole connector will require the servo headers on the back of the board to be dropped". Why is it required?

**Comment by kwagyeman** [comment]
They run under the USB header.
