### ISSUE TITLE
Software: Add transpose to sensor module.

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv#137]
The sensor module needs the ability to transpose images. Basically, after a line has been captured by the DCMI you swap X and Y pointers when writing that line into the frame buffer. Something like "set_transpose(enable)" would be all that we'd need.

With this feature you can now do rotations when you combine transpose with hmirror and vflip.

0 degrees: transpose(off), vflip(off)
90 degrees: transpose(on), vflip(on)
180 degrees: transpose(off), vflip(on)
270 degrees: transpose(on), vflip(off)

**Comment by iabdalkader** [comment]
This has been implemented.
