### ISSUE TITLE
win10 can not connect to IDE

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#138]
In Ubuntu, all is fine.
in win10, when I plugged in usb, the drivers are automatic installed, mass storage and vitual port are OK.
But, when I opened the IDE, and click "connect", there is a dialog.
![image](https://cloud.githubusercontent.com/assets/9582040/15387000/408ca6fe-1ddd-11e6-8a75-5cb60df2b01d.png)

is the driver error? or I didn't install libusb?
how could I solve the problem?

thank you

**Comment by kwagyeman** [comment]
Hi, please post issues to the forum.

**Comment by iabdalkader** [comment]
I think this is an issue with an older IDE/FW going to close, please re-open if you're still having the same issue with v1.5
