### ISSUE TITLE
AttributeError: 'module' object has no attribute 'B64x32'

### ISSUE THREAD

**Issue by mindThomas** [openmv/openmv#145]
OpenMV Cam 2 updated to the latest firmware pulled from the master Git branch in the firmware folder.
When running some of the examples within the new IDE, probably some of the later Micro Python v1.4.5 type of examples, I get different kind of library errors.

One of the errors, running the Optical Flow example, is: "AttributeError: 'module' object has no attribute 'B64x32'"

**Comment by kwagyeman** [comment]
Yes, this will be fixed in the upcoming IDE release. The IDE was really just a preview version and the firmware wasn't in sync with the examples.

**Comment by iabdalkader** [comment]
Fixed.

**Comment by JAYPENGXu** [comment]
so,how can we solve it
