### ISSUE TITLE
No value for Inductors and crystal

### ISSUE THREAD

**Issue by alexandrewillame** [openmv/openmv#146]
There are no indication on the values of the inductors used in the project, or the crystal. What are the values for those components?

Regards,

**Comment by iabdalkader** [comment]
Not sure which board you're talking about, however the crystal is typically 12MHz, and that's probably a ferrite bead (TDK MPZ series).

**Comment by alexandrewillame** [comment]
It was on the openmv2 that I saw. Thanks for the information!

**Comment by maurbeck** [comment]
Is the BOM for openMV1 or 2?

https://github.com/openmv/openmv/blob/master/eagle/openmv2/BOM.ods

**Comment by maurbeck** [comment]
Well, nevemind, lol. I see clearly now that it's 2.
