### ISSUE TITLE
new v1.8 firmware doesn't like microSD cards

### ISSUE THREAD

**Issue by mad474** [openmv/openmv#148]
With old firmware
`Micro Python v1.4.4-189-g4f6880b on 2016-05-03; OPENMV2 with STM32F427
`
powering up with inserted microSD card everything looks fine:
```
>>> import os
>>> os.getcwd()
'1:/'
```

With new (well, 2 days old) firmware binary (https://github.com/openmv/openmv/blob/master/firmware/OPENMV2/openmv.dfu):
`MicroPython v1.8-4338-g200e05f on 2016-08-14; OPENMV2 with STM32F427
`
powering up with inserted microSD card (the same tested working as before) leads to white led and "stuck system" (can't get REPL in terminal emulation).

Leaving microSD card away is "o.k.":
```
>>> import os
>>> os.getcwd()
'0:/'

```
Tested by reflashing back and forth.

**Comment by iabdalkader** [comment]
Fixed, thanks for pointing that out.
