### ISSUE TITLE
PICO/RP2 allocates more vbuffers than available.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv#1505]
**To Reproduce**
This is hard to reproduce without my custom sensor kit, but I could help with testing.

**Expected behavior**
Expected to allocate 1 buffer.

**Screenshots**
![image](https://user-images.githubusercontent.com/4498013/150032676-c9f3d033-b8ad-4eff-93d0-4d966bacff11.png)

**Please complete the following information**
 - IDE version: [latest]
 - Firmware version: [latest]
 - Board: [PICO, NANO-RP2040]
 - OS: [Linux]

**Comment by kwagyeman** [comment]
Can they send me this board?

**Comment by kwagyeman** [comment]
Maybe this? https://github.com/openmv/openmv/pull/1506

**Comment by kwagyeman** [comment]
I'd put printf here:

`void framebuffer_auto_adjust_buffers()
{
     // Keep same buffer count in video fifo mode but resize buffer sizes.
    if (framebuffer->n_buffers > 3) {
        framebuffer_set_buffers(framebuffer->n_buffers);
        return;
    }

    for (int i = 3; i > 0; i--) {
        framebuffer_set_buffers(i);

        // Find a buffering size automatically that doesn't use more than half.
        if (fb_avail() >= framebuffer_total_buffer_size()) {
            return;
        }
    }
}`

And just print out what the numbers are each loop. Issue should be obvious.

**Comment by iabdalkader** [comment]
> Can they send me this board?

This my own custom breakout for Pico. I'll try the above later.
