### ISSUE TITLE
Camera crashes when IDE overwrites the currently running script

### ISSUE THREAD

**Issue by petri** [openmv/openmv#152]
(originally https://github.com/openmv/openmv-ide/issues/5)

Steps to reproduce:
1. connect camera
2. start a script on it, from camera SD card
3. while the script is still running, make some changes and re-save (via IDE), ie. overwrite the script currently running on the camera

There will usually be different errors, apparently depending on the actual changes to the script. The only way to recover is to physically disconnect-reconnect the USB.

The crash does not always happen - it seems the more there are changes to the script, the higher the likelihood of crash.

**Comment by iabdalkader** [comment]
@kwagyeman Is this related to the issue you were talking about ?

**Comment by kwagyeman** [comment]
Old issue.
