### ISSUE TITLE
Feature Request: Support High temperature modes on FLIR Lepton 3.5 sensor

### ISSUE THREAD

**Issue by linknum23** [openmv/openmv#1534]
The FLIR Lepton 3.5 sensor has a high temperature output mode that supports temperature readings up to 600C.

A couple of things need to be added to support this:
- Add min and max temperature setting firmware
- Add flag for enabling high temperature mode

I have a working prototype of the changes as additions to the IOCTL interface, does it make sense to submit them as a PR?

**Comment by iabdalkader** [comment]
Yes please send it for review.

**Comment by iabdalkader** [comment]
Implemented in https://github.com/openmv/openmv/pull/1542
