### ISSUE TITLE
OpenMV Pure Thermal  RTC 

### ISSUE THREAD

**Issue by weilian1977** [openmv/openmv#1536]
OpenMV Pure Thermal，connected a battery to VBATT，VBATT_RTC can output 3.0V even when power off，but when power off RTC clock can only keep the time of power off time while not increment。firmware 4.2.1

**Comment by iabdalkader** [comment]
This should be fixed now.. Try [v4.2.3](https://github.com/openmv/openmv/releases/tag/v4.2.3) ? When you start/stop a script it should print in the terminal `OpenMV v4.2.3`  to be sure you have the right firmware.

**Comment by weilian1977** [comment]
Now I confirm  firmware is v4.2.3，test result is still keep the time while not increment。
The test method is connect a battery(3.6V) to VBATT,then connect Pure Thermal board  connect Pure Thermal board to computer through usb cable,power on Pure Thermal board,set RTC time,power off Pure Thermal board while keep usb cable connect Pure Thermal board and computer ,wait about 10min,power on Pure Thermal board,get RTC time.

**Comment by weilian1977** [comment]
read  RCC_BDCR Register   hex(stm.mem32[0x58024400+0x70]) is 0x8203, 8 means  RTC clock enable，2 means RTC clock source selection is LSI，3 means that LSE oscillator ready and LSE oscillator enabled, so RTC clock source  is LSI.

**Comment by iabdalkader** [comment]
@weilian1977 is the issue fixed ?

**Comment by weilian1977** [comment]
https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip&nbsp; V4.2.4&nbsp;&nbsp;print(hex(stm.mem32[0x58024400+0x70]))=0x8200&nbsp; &nbsp; not increase


https://github.com/openmv/openmv/releases/download/v4.2.3/firmware_v4.2.3.zip&nbsp;&nbsp;
V4.2.3&nbsp;&nbsp;print(hex(stm.mem32[0x58024400+0x70]))=0x8200&nbsp; &nbsp; not increase
disconnect battary then power on&nbsp;&nbsp;
time&nbsp; is (2015, 1, 1, 4, 0, 0, 7, 222656)
 
print(hex(stm.mem32[0x58024400+0x70]))=0x8200
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmv/openmv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月18日(星期五) 上午10:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmv/openmv] OpenMV Pure Thermal  RTC  (Issue #1536)





 
Yes that's right.. I pushed another fix, please try the latest development release again.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iabdalkader** [comment]
This is not the development release. Please try this: https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip

**Comment by weilian1977** [comment]
download（https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip），StmCubeProgrammer download the openmv.bin，IDE show version is 4.2.4，print(hex(stm.mem32[0x58024400+0x70]))=0x8205，no increase，test C96 C97 C110 C111，there are on 32.768 signal。
print(rtc.datetime())=(2022, 2, 22, 2, 8, 10, 35, 605468).

**Comment by weilian1977** [comment]
Need to disconnect the battery after burning the firmware？

**Comment by weilian1977** [comment]
download（[https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip），StmCubeProgrammer download the openmv.bin，disconnect the battery after burning the firmware about 5 min，IDE show version is 4.2.4，print(hex(stm.mem32[0x58024400+0x70]))=0x8200，no increase，test C96 C97 C110 C111，there are on 32.768 signal。

**Comment by iabdalkader** [comment]
> disconnect the battery after burning the firmware about 5 min

You **should never disconnect the battery**, if you want the RTC to keep working it needs a power source.

**Comment by weilian1977** [comment]
when I test RTC，I never disconnect the battery。

**Comment by iabdalkader** [comment]
Okay I see an issue, wait will update the dev release.

**Comment by iabdalkader** [comment]
Hi, try it again now, it should be working. I made sure RTC is using LSE now.

https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip

**Comment by weilian1977** [comment]
the firmware can not power on OPENMVPT，I download it two times and burning the firmware  two times

**Comment by iabdalkader** [comment]
Will debug and get back to you.

**Comment by iabdalkader** [comment]
@weilian1977 The wrong LSE mode was used, I fixed it now and the RTC clock source should LSE. Please test again and let me know how it goes.
Same link: https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip

**Comment by iabdalkader** [comment]
Hi, the firmware should be working, but there's an issue with the LSE crystal. The crystal load caps are too high so the LSE doesn't start, and the firmware blocks in a loop waiting for the LSE to start. I disabled the early LSE/RTC config, so the firmware shouldn't block anymore, and left the RTC clock source in Micropython set to LSE. However, the RTC will Not work unless capacitors `C96` and `C97` are removed.

**Comment by weilian1977** [comment]
Thanks a lots.I will remove&nbsp;C96&nbsp;and&nbsp;C97(noly&nbsp;C96&nbsp;&nbsp;&nbsp;C97?),which&nbsp;firmware&nbsp; can test?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmv/openmv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 晚上10:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmv/openmv] OpenMV Pure Thermal  RTC  (Issue #1536)





 
Hi, the firmware should be working, but there's an issue with the LSE crystal. The crystal load caps are too high so the LSE doesn't start, and the firmware blocks in a loop waiting for the LSE to start. I disabled the early LSE/RTC config, so the firmware shouldn't block anymore, and left the RTC clock source in Micropython set to LSE. However, the RTC will Not work unless capacitors C96 and C97 are removed.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iabdalkader** [comment]
Same link above, development release. It gets updated after every change. Please let us know how it goes.

**Comment by weilian1977** [comment]
OK！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmv/openmv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 上午8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmv/openmv] OpenMV Pure Thermal  RTC  (Issue #1536)





 
Same link above, development release. It gets updated after every change. Please let us know how it goes.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iabdalkader** [comment]
For reference, these are the capacitors that need to be removed:

![image](https://user-images.githubusercontent.com/4498013/156196677-cc25c7f9-f72f-4afa-91bb-c33ff2501bfc.png)

**Comment by weilian1977** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmv/openmv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 晚上11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmv/openmv] OpenMV Pure Thermal  RTC  (Issue #1536)





 
For reference, these are the capacitors that need to be removed:
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weilian1977** [comment]
1、capacitors was removed；
2、firmware is&nbsp; https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip
3、power off openmvPT and disconnect battery；
4、connect battery；
5、power on openmvPT by usb；
6、rtc.datetime((2022, 3, 2, 2, 14, 56, 00, 0)) set time 
7、print(hex(stm.mem32[0x58024400+0x70]))  == 0x81038、power off openmvPT by SW1（PWR ON/OFF ） in PTOMV_Schematics_revE_prelim.PDF page2  while connect battery；9、power on openmvPT by SW1（PWR ON/OFF ） in PTOMV_Schematics_revE_prelim.PDF page2  while connect battery；10、print(rtc.datetime())= 0:0:3011、print(hex(stm.mem32[0x58024400+0x70]))  == 0x8203




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmv/openmv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月1日(星期二) 晚上11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmv/openmv] OpenMV Pure Thermal  RTC  (Issue #1536)





 
For reference, these are the capacitors that need to be removed:
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iabdalkader** [comment]
> 11、print(hex(stm.mem32[0x58024400+0x70]))  == 0x8203

Does the RTC increment ? I see the RTC clock source is switched back to LSI on reset, I pushed another fix. Please test again with the same link above.

**Comment by weilian1977** [comment]
power off （&nbsp;RTC battery is connect ）will cause RTC clock source from lse switched LSI，and time to 0：0：0：


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmv/openmv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmv/openmv] OpenMV Pure Thermal  RTC  (Issue #1536)





  
11、print(hex(stm.mem32[0x58024400+0x70]))  == 0x8203
  
Does the RTC increment ? I see the RTC clock source is switched back to LSI on reset, I pushed another fix. Please test again with the same link above.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iabdalkader** [comment]
Did you test again ? I made sure the LSE source is not changed on reset.

**Comment by weilian1977** [comment]
need new firmware？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmv/openmv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmv/openmv] OpenMV Pure Thermal  RTC  (Issue #1536)





 
Did you test again ? I made sure the LSE source is not changed on reset.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by iabdalkader** [comment]
Yes, same link it gets updated. https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip

**Comment by weilian1977** [comment]
1、capacitors was removed；
2、firmware is&nbsp;&nbsp;https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip
&nbsp; &nbsp; &nbsp; &nbsp;info:MicroPython: 188f051 OpenMV: 68eb6ca HAL: v1.9.0 BOARD: OPENMVPT-STM32H743
3、power off openmvPT and disconnect battery；
4、connect battery；
5、power on openmvPT by usb；
6、rtc.datetime((2022, 3, 3, 4, 18, 58, 00, 0)) set time&nbsp; &nbsp;(set time code and result)

7、print(hex(stm.mem32[0x58024400+0x70]))  = 0x8103   (set test code code and result1)8、power off openmvPT by SW1（PWR ON/OFF ） in Schematics_revE_prelim.PDF page2  while connect battery；9、power on openmvPT by SW1（PWR ON/OFF ） in Schematics_revE_prelim.PDF page2  while connect battery；10、print(rtc.datetime())= 2000, 1, 1, 1, 0, 0, 31, 734375    (set test code code and result2)11、print(hex(stm.mem32[0x58024400+0x70]))  == 0x8203    (set test code code and result2)


set time codeimport timefrom pyb import RTCrtc = RTC()rtc.datetime((2022, 3, 3, 4, 18, 58, 00, 0))while (True):    print(rtc.datetime())    time.sleep_ms(1000)
result:
(2022, 3, 3, 4, 18, 58, 43, 191406)

0x8103


test codeimport timefrom pyb import RTCimport stmrtc = RTC()#rtc.init()#stm.mem32[0x58024400+0x70]=0x8103print(hex(stm.mem32[0x58024400+0x70]))print(hex(stm.mem32[0x58024800]))while (True):    print(rtc.datetime())    print(hex(stm.mem32[0x58024400+0x70]))    time.sleep_ms(1000)result2:
0x8103

-0xfff3f00

(2022, 3, 3, 4, 18, 58, 38, 335937)

0x8103

(2022, 3, 3, 4, 18, 58, 39, 304687)

0x8103

(2022, 3, 3, 4, 18, 58, 40, 277343)






result3:
0x8203

-0xfff3f00

(2000, 1, 1, 1, 0, 0, 28, 847656)

0x8203

(2000, 1, 1, 1, 0, 0, 29, 808593)

0x8203

(2000, 1, 1, 1, 0, 0, 30, 769531)

0x8203








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmv/openmv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 晚上6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmv/openmv] OpenMV Pure Thermal  RTC  (Issue #1536)





 
Yes, same link it gets updated. https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weilian1977** [comment]
1、capacitors was removed；
2、firmware is&nbsp;&nbsp;https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip
&nbsp; &nbsp; &nbsp; &nbsp;info:MicroPython: 188f051 OpenMV: 68eb6ca HAL: v1.9.0 BOARD: OPENMVPT-STM32H743
3、power off openmvPT and disconnect battery；
4、connect battery；
5、power on openmvPT by usb；
6、rtc.datetime((2022, 3, 3, 4, 18, 58, 00, 0)) set time&nbsp; &nbsp;(set time code and result)

7、print(hex(stm.mem32[0x58024400+0x70]))  = 0x8103   (test code code and result)8、power off openmvPT by SW1（PWR ON/OFF ）9、power on openmvPT by SW1（PWR ON/OFF ）10、print(rtc.datetime())= 2000, 1, 1, 1, 0, 0, 31, 734375    (test code code and result2)11、print(hex(stm.mem32[0x58024400+0x70]))  == 0x8203    (test code code and result3)
12、rtc.datetime((2022, 3, 3, 4, 19, 13, 20, 0)) &nbsp;set time&nbsp; &nbsp;(set time code and result)
13、print(hex(stm.mem32[0x58024400+0x70]))  = 0x8203   (test code code and result4)14、power off openmvPT by SW1（PWR ON/OFF ）      wait one min15、power on openmvPT by SW1（PWR ON/OFF ）16、print(rtc.datetime())  (set test code code and result5)17、print(hex(stm.mem32[0x58024400+0x70]))  == 0x8203    (test code code and result5)



set time codeimport timefrom pyb import RTCrtc = RTC()rtc.datetime((2022, 3, 3, 4, 18, 58, 00, 0))while (True):    print(rtc.datetime())    time.sleep_ms(1000)
result:
(2022, 3, 3, 4, 18, 58, 43, 191406)

0x8103


test codeimport timefrom pyb import RTCimport stmrtc = RTC()#rtc.init()#stm.mem32[0x58024400+0x70]=0x8103print(hex(stm.mem32[0x58024400+0x70]))print(hex(stm.mem32[0x58024800]))while (True):    print(rtc.datetime())    print(hex(stm.mem32[0x58024400+0x70]))    time.sleep_ms(1000)result2:
0x8103

-0xfff3f00

(2022, 3, 3, 4, 18, 58, 38, 335937)

0x8103

(2022, 3, 3, 4, 18, 58, 39, 304687)

0x8103

(2022, 3, 3, 4, 18, 58, 40, 277343)






result3:
0x8203

-0xfff3f00

(2000, 1, 1, 1, 0, 0, 28, 847656)

0x8203

(2000, 1, 1, 1, 0, 0, 29, 808593)

0x8203

(2000, 1, 1, 1, 0, 0, 30, 769531)

0x8203







result4:

0x8203
 
-0xfff3f00
 
(2022, 3, 3, 4, 19, 14, 43, 792968)
 
0x8203
 
(2022, 3, 3, 4, 19, 14, 44, 753906)
 
0x8203







result5:

0x8203
 
-0xfff3f00
 
(2022, 3, 3, 4, 19, 16, 56, 636718)
 
0x8203
 
(2022, 3, 3, 4, 19, 16, 57, 597656)
 
0x8203
 
(2022, 3, 3, 4, 19, 16, 58, 558593)
 
0x8203
 
(2022, 3, 3, 4, 19, 16, 59, 523437)
 
0x8203





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openmv/openmv"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 晚上6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openmv/openmv] OpenMV Pure Thermal  RTC  (Issue #1536)





 
Yes, same link it gets updated. https://github.com/openmv/openmv/releases/download/development/firmware_OPENMVPT.zip
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by weilian1977** [comment]
now it is ok！

**Comment by iabdalkader** [comment]
Can you post the test result ?

**Comment by weilian1977** [comment]
computer time   8:57:54,PT time   8:57:09      35  second
computer time 12:43:26,PT time 12:42:35      51  second 

print(hex(stm.mem32[0x58024400+0x70]))=0x8103
print(hex(stm.mem32[0x58024800])) = -0xfff3f00
Now LSE is work,  time can increase with battery connect to PCB board while power off STM32 CPU.But PT time is slower 16 second in about 4 hours。

**Comment by kwagyeman** [comment]
Yeah, the LSE probably needs tuning:

https://blog.fearcat.in/a?ID=01600-39c8277a-985b-4709-9205-b459f40e3d36

**Comment by iabdalkader** [comment]
@weilian1977 Can you please test this new firmware ? I made a new fix for RTC should work on boards with/without caps.
[openmvpt.zip](https://github.com/openmv/openmv/files/8202392/openmvpt.zip)

**Comment by weilian1977** [comment]
can not power on

**Comment by iabdalkader** [comment]
Hi, I merged a new fix for boards with/without caps and we tested it, it should be working.. Closing this issue.

**Comment by weilian1977** [comment]
where to download the firmware?

**Comment by iabdalkader** [comment]
Same link: https://github.com/openmv/openmv/releases/tag/development

**Comment by weilian1977** [comment]
Now is OK

**Comment by iabdalkader** [comment]
@weilian1977 That's great! Thank you for all the testing.
