### ISSUE TITLE
"Save open script to openMV cam" menu button greyed out

### ISSUE THREAD

**Issue by kdarras** [openmv/openmv#1574]
I have a feeling this happens since the latest IDE was released.
The button is regularly grey and unselectable with several, but not all of my H7+ boards, even though they are connected to the IDE, whether there is a main.py file already on the SD card or not.
Running Ubuntu 20.04

**Comment by iabdalkader** [comment]
Fixed.

**Comment by gcl8a** [comment]
I just encountered this issue on two different M1 macbooks. In both cases, the option is grayed out. On my machine, the camera is mounted as "FAT12" according to the Disk Utility app (not sure about the other, but I presume it's the same).

**Comment by iabdalkader** [comment]
@gcl8a Which issue are you referring to ? There was something missing in code that created new filesystems, and I fixed that. If there's an issue on M1 it might be an IDE issue. You could also try erasing the filesystem from the IDE.
