### ISSUE TITLE
First frame has corrupted lines.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv#1580]
**Describe the bug**
The first frame (technically the second, since we skip the first) shows corrupted lines when setting a window. It's very likely a cache flush/invalidate issue.

**To Reproduce**
```python
import sensor, image, time

sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.set_framebuffers(1)
sensor.set_windowing((0, 0, 240, 240))
sensor.snapshot().flush()
time.sleep_ms(5000)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4498013/157489470-4a64c965-fe4e-4a3a-85dc-9de563d992b6.png)

**Please complete the following information**
 - IDE version: [latest]
 - Firmware version: [latest]
 - Board: [OPENMV-4]
 - OS: [Linux]

**Comment by iabdalkader** [comment]
CC @kwagyeman

**Comment by kwagyeman** [comment]
I can't for the life of me figure out what's causing this. It seems to be highly correlated with sensor.set_windowing((0, 0, 240, 240)). Removing that line removes the issue. It's something to do with windowing being setup. In particular framebuffer->u/framebuffer->v not being equal to the frame size.

**Comment by kwagyeman** [comment]
Doesn't seem to have anything to do with jpeg. If I to_png() the image before flush then it still will have the bar. Also, the bar appears to be in the same sport per frame.

**Comment by kwagyeman** [comment]
Determined why this happens:

sensor.set_framebuffers(1)
sensor.set_windowing((0, 0, 240, 240))

Doesn't set the frame buffer count to 1. When you do set windowing it resets it back to 3 as the frame buffers auto adjust when you change settings around.

After which, the MDMA writes to the tail image buffer which is different than the head image buffer that's invalidated when snapshot() is called.

So, the solution is invalidate all non-head buffers.

PR coming soon.

**Comment by kwagyeman** [comment]
https://github.com/openmv/openmv/pull/1605

**Comment by iabdalkader** [comment]
@kwagyeman don't close issues.

**Comment by kwagyeman** [comment]
Why? I found the fix?

**Comment by iabdalkader** [comment]
@kwagyeman When it's merged the issue will be closed automatically as long as it's linked to a PR. As for the fix, I need to understand it better, I already invalidate buffers before they are returned to the user.
