### ISSUE TITLE
Nano RP2040 Connect Micropython Thermal Camera Demo: Failed to detect any FIR sensor

### ISSUE THREAD

**Issue by jomoengineer** [openmv/openmv#1584]
I am attempting to run the Thermal Camera Demo for the Arduino Nano RP2040 Connect From the OpenMV IDE but it is failing to detect the board.  I am using a SparkFun Qwiic GRID-Eye Infrared Array (AMG88xx) board which has an address of 0x69.

This is what the the i2c_scanner.py script shows:

```
Scanning bus 0...
Found device at addres 0:0x60
Found device at addres 0:0x69
Found device at addres 0:0x6a

Scanning bus 1...

```
NOTE: The GRID-Eye device shows as address 0:0x69, or rather 'addres' 0x69. Spelling error?

The error from the thermal_camera.py script shows:
```
Traceback (most recent call last):
  File "<stdin>", line 12, in <module>
ValueError: Failed to detect any FIR sensor
MPY: soft reboot
MicroPython: v1.17-omv-r22 OpenMV: v4.2.3 HAL: v1.3.0 BOARD: Arduino Nano RP2040 Connect-RP2040
Type "help()" for more information.
>>> 
```
![image](https://user-images.githubusercontent.com/10980402/157604097-32a034f5-62ed-4c45-abaf-657a7948d9e8.png)

Am I missing something with this example?

IDE version: 2.9.0
Firmware version: 4.2.3
Board: Arduino Nano RP2040 Connect
OS: Windows 10

**Comment by iabdalkader** [comment]
The fir sensor needs to be on this bus/pins:

```C
#define FIR_I2C_ID              (0)
#define FIR_I2C_SCL_PIN         (13)
#define FIR_I2C_SDA_PIN         (12)
```

**Comment by jomoengineer** [comment]
@iabdalkader 
Thanks again.  I reconnected the GRID-Eye  using the header pins rather than the Qwiic connector and then connected the INT (Interrupt pin) to GPIO0 of the Nano RP2040 and it still does not find the GRID-Eye device.  It still shows as address 0x69 in the i2c_scanner..py output though.  

Note: There is no ID pin on the GRID-Eye device, just an INT Pin.

**Comment by iabdalkader** [comment]
You don't need the INT pin, only GND, 3.3V and SCL, SDA connected to A5 and A4. The auto-detection doesn't seem to be working well, so just set the sensor type like this:
```
....
fir.init(fir.FIR_AMG8833)
....
```

**Comment by jomoengineer** [comment]
Okay, yeah that worked.

Could this be that the AMG8833_ADDR in the py_fir.c file is set to 0xD2?
```
#define AMG8833_ADDR                    0xD2
```
Thanks.
