### ISSUE TITLE
Converting loaded jpegs to RGB565 introduces color shift

### ISSUE THREAD

**Issue by kdarras** [openmv/openmv#1597]
When loading a jpeg saved on the SD card root, converting it to RGB565 and saving it as JPEG again, the resulting image will have a visible shift in color (less reddish)

1. Take full-resolution image(s) with the H7+ board (sensor.RGB565, sensor.snapshot(), img.save("xxx.jpeg",quality=92))
2. Copy jpeg(s) to SD card root
3. Run this:

```python
import image, os
if not "output" in os.listdir(): os.mkdir("output")
#scan jpegs on card
files=os.listdir()
jpegs=[files for files in files if "jpg" in files]

for jpeg in jpegs:
    img=image.Image(jpeg,copy_to_fb=True)
    print("original loaded image:",img)
    img.save("straight_"+jpeg)
    
    img.to_rgb565()
    print("rgb565-converted image:",img)
    img.save("torgb_"+jpeg)

```
4. Observe the non-converted ("straight") and rgb565-converted ("torgb565") images

I expected the script and board to output pictures with unaltered colors, whether they were converted to rgb565 or not. Instead, I get visibly different images:

Original image, loaded and then saved again as JPEG (it looks identical to the image zipped and attached below at the end of the post):
![straight_0 - dummy](https://user-images.githubusercontent.com/7696198/159822565-a14a819b-5f44-4037-964a-157d826ac24b.jpg)

Original image, converted to RGB565, and then saved as JPEG:
![torgb_0 - dummy](https://user-images.githubusercontent.com/7696198/159822607-a1118136-181c-4b0f-9242-1222f1327a54.jpg)

Original image:
[0 - dummy.zip](https://github.com/openmv/openmv/files/8337639/0.-.dummy.zip)

 - IDE version: 2.9.0
 - Firmware version: 4.3.0
 - Board: OPENMV-H7+
 - OS: Linux

**Comment by iabdalkader** [comment]
@kdarras 

I didn't test this, but note the following

```python
img.save("torgb_"+jpeg)
```
Will compress the image using the default quality which 50%, you can pass a quality arg to `save()`:
```python
img.save("torgb_"+jpeg, quality=92)
```

**Comment by kdarras** [comment]
I tried it to be be sure, but it did not make a difference. Even low JPEG quality settings should not introduce systematic color shifts (and note that the non-converted image was also saved with the same settings, and did not have a color shift).

**Comment by kwagyeman** [comment]
Hardware jpeg support mainlined: https://github.com/openmv/openmv/pull/1604

**Comment by iabdalkader** [comment]
I really think the software decoder should also be fixed, if there's an issue with it, only the H7 has HW JPEG.

**Comment by kwagyeman** [comment]
Yes, @bitbank2

**Comment by bitbank2** [comment]
I'll look at the code

**Comment by bitbank2** [comment]
I just tested this with the attached images on the latest code on the H7+ board. The output loses a little color fidelity, but doesn't turn reddish. Attached are the input and output images I used for testing:

![straight_teensy4](https://user-images.githubusercontent.com/9803883/161400277-472cb250-8c3c-428c-b901-43179de7cd51.jpg)
![torgb_teensy4](https://user-images.githubusercontent.com/9803883/161400280-66aeb8cc-33d8-4518-a4b5-4242971f2339.jpg)
![teensy4](https://user-images.githubusercontent.com/9803883/161400286-c65d2afb-f72b-4ee7-9173-788a39c053d7.jpg)

**Comment by iabdalkader** [comment]
It could be a rounding issue when converting to RGB565.

**Comment by kdarras** [comment]
Hi there, it's about the picture becoming less reddish, @bitbank2 . I just tested it with fresh images (which may need to contain some red to be able to see the shift) on a 4.3.1 firmware H7+ board and the color shift remains.

**Comment by bitbank2** [comment]
I found the source of the problem - it's in the JPEGPixelLE and JPEGPixelLE2 methods. The saturation of the color values is not equivalent to the C code I had before with lookup tables. Working on a fix to the SIMD code to avoid adding back 3 x 2K byte tables into FLASH.

**Comment by bitbank2** [comment]
Just checked in a fix to my fork:

https://github.com/bitbank2/openmv/commit/981d677e327f68c6b4fe717228bc048d586013f7

**Comment by iabdalkader** [comment]
@bitbank2 Does it fix the issue and do you want me to commit it ?

**Comment by bitbank2** [comment]
Yes, it fixes the issue

**Comment by bitbank2** [comment]
I create a PR
https://github.com/openmv/openmv/pull/1611
