### ISSUE TITLE
PureThermal Glitchy Display with fw 4.3.0

### ISSUE THREAD

**Issue by griffin175** [openmv/openmv#1599]
**Describe the bug**
Glitchy display on every unit flashed with 4.3.0 that I have tested.
6 units tested. 5 out of 6 have had C96 and C97 removed from the RTC crystal.
Happens over HDMI or the onboard display.

**To Reproduce**
1. Flash fw 4.3.0
2. Observe

**To fix**
Flash 4.3.1 (currently the dev release) or the older 4.2.3.

**Screenshots**
Glitch on built in display:
![image](https://user-images.githubusercontent.com/56269216/160465293-55b20de6-03a8-47c5-b164-bcdb063826fa.png)
![image](https://user-images.githubusercontent.com/56269216/160465367-a08dd4ab-5582-418f-b0e8-f436f845e93d.png)

Glitch on HDMI output:
![image](https://user-images.githubusercontent.com/56269216/160464974-8e237237-02ba-4853-bf72-6470480b353a.png)
![image](https://user-images.githubusercontent.com/56269216/160465064-1392e872-a4a1-4faa-ba8b-dab4773d113b.png)

 - IDE version: IDE 2.9.0
 - Firmware version: fw 4.3.0
 - Board: PureThermal OpenMV
 - OS: flashing from Windows 11

**Comment by kwagyeman** [comment]
I managed to cause a wavey lines issue. Then it went away. Different from this... but, signs point to hardware issues.

**Comment by kwagyeman** [comment]
This fixes a different issue I was seeing when you'd connect the device to the PC and interrupt the running script and then run it again: https://github.com/openmv/openmv/pull/1607

As for the wavey lines. I need to test more. The wavey line issue isn't easily to reproduce. Still not clear what is causing it.

**Comment by kwagyeman** [comment]
As for the above glitch... I used to see that. But, I only get an issue where the display is completely wavey. I don't see the partial image buffer glitch anymore.

**Comment by iabdalkader** [comment]
> The wavey line issue isn't easily to reproduce

I think the wavey lines might have something to do with USB storage mounting, I used to see this with normal cams when the host mounts the USB storage and read/write blocks, all IRQs are disabled. Easy way to confirm this is to disable the USB storage.

**Comment by iabdalkader** [comment]
I don't see this issue either with the dev-release.

**Comment by iabdalkader** [comment]
@griffin175 Is this issue fixed ?

**Comment by griffin175** [comment]
@iabdalkader Yes, current release (v4.3.1) is good!
