### ISSUE TITLE
Is DSP (STM32H743VI) used in the MicroPython on the OpemMV H7?

### ISSUE THREAD

**Issue by beyonlo** [openmv/openmv#1616]
Hi all.

I see that the OpenMV Cam H7 use the STM32H743VI, where this MCU has a DSP embedded. I would like to know if the MicroPython does use (in Python) of that DSP instructions on the OpemMV H7. If yes, could you please point me a example?

Thank you.

**Comment by kwagyeman** [comment]
The DSP instructions we do use. However, it's not another processor. It's just different instructions as part of the Cortex-M7 core: https://www.keil.com/pack/doc/cmsis/Core/html/group__intrinsic__SIMD__gr.html

Here's an example of how to use them: https://github.com/openmv/openmv/blob/master/src/omv/ports/stm32/modules/py_tv.c#L619
