### ISSUE TITLE
sensor.set_pixformat(sensor.RGB565) error on OpenMV Cam H7

### ISSUE THREAD

**Issue by airsalutanonymous** [openmv/openmv#1626]
Hello, 

I am trying to set my camera sensor to RGB, but I can't.
I have read a lot on this issue, but it seems that my camera support RGB: https://www.sparkfun.com/products/retired/15325
This is the model I have. 

Something I don't understand is I can see the GGB color space [histograms) on OpenMV? Why, If I can take only grayscale images? 

Thanks, 
Hugo 

Error message:
ValueError: Sensor control Failed!

```
import sensor, image, time

sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.set_auto_whitebal(False)
sensor.skip_frames(time = 2000)

clock = time.clock()

while(True):
    clock.tick()
    img = sensor.snapshot()
    print(clock.fps())

```

**Comment by kwagyeman** [comment]
Is the camera mounted correct?

**Comment by airsalutanonymous** [comment]
What do you mean by mounted correct? 

![image](https://user-images.githubusercontent.com/102857776/164996150-aaaf0008-4047-48df-803b-1e4f1b7dd278.png)

Back of my sensor: 
![image](https://user-images.githubusercontent.com/102857776/164996169-565a6af0-4b81-4e81-8f09-6d20bc21ce81.png)

**Comment by kwagyeman** [comment]
You have the global shutter sensor installed which is grayscale only.
