### ISSUE TITLE
Unable to build firmaware

### ISSUE THREAD

**Issue by tejalbarnwal** [openmv/openmv#1632]
**Describe the bug**
I have recently forked the original repository to build the firmware to run the model on the NICLA Vision sensor. The firmware build fails at the development release step.

**To Reproduce**
I have replaced the files in the `openmv/src/lib/libtf/models/` by my [`.bin`](https://github.com/tejalbarnwal/openmv/tree/master/src/lib/libtf/models) and [`.txt`](https://github.com/tejalbarnwal/openmv/tree/master/src/lib/libtf/models) file obtained from Edge Impulse and OpenMV dataset respectively. Upon the activating the github action, I receive an error stating 
`🌶  failed to delete ref "refs/tags/development" <- Resource not accessible by integration`
`🌶  An error occured while deleting the tag "development"`

**Screenshots**
![image](https://user-images.githubusercontent.com/64950661/167681992-e6d5dd51-0a2f-4b0b-955c-41b3b8b4d7bf.png)

**Please complete the following information**
 - IDE version: 2.9.0
 - Firmware vesion: latest, directly forked `master` (https://github.com/tejalbarnwal/openmv)
 - Board: Arduino Nicla Vision
 - OS: Windows

**Comment by iabdalkader** [comment]
Try creating the `development` tag, i.e:

```bash
git tag development
git push origin development
```

**Comment by tejalbarnwal** [comment]
The tag `development` already exists. Also, does this push has to go to the `development` branch.? To deploy the model from the edge impulse, I went into the deployment section in the menu of edge impulse, selected OpenMV under "Build firmware" and clicked "build" with quantized optimization as stated [here in the Deploy section](https://docs.arduino.cc/tutorials/nicla-vision/image-classification). The `.zip` file that gets downloaded returns `.bin` files and not `.tflite`.

**Comment by iabdalkader** [comment]
I think that `bin` you have is a firmware image with the model embedded.

This, what you're trying to do, is something else entirely. This is to add your own built-in model and build the firmware from source (the easy way).

Note your screenshot doesn't show the errors, just that something fails, I'm not sure if I'm missing something.

> Also, does this push has to go to the development branch

There's no development branch, and the tag isn't needed either (I forgot that we don't need that anymore). I'll fork the repo and see what's wrong.

**Comment by tejalbarnwal** [comment]
Yes, right! I meant the `delete old release` step is giving the same original error. I am not sure but could it be an issue related to `GITHUB_TOKEN`?
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token indicates for forked repos the `GITHUB_TOKEN` only has ‘read’ permission

**Comment by iabdalkader** [comment]
> . I am not sure but could it be an issue related to GITHUB_TOKEN?

No, it's because the development release doesn't exist, so that step fails and the workflow fails. I'm trying to fix it.

**Comment by iabdalkader** [comment]
I think you can fix it in your fork, but I also want to fix it in the workflow.

![image](https://user-images.githubusercontent.com/4498013/167874475-69970be4-821d-4e69-b55a-47404341af34.png)

**Comment by tejalbarnwal** [comment]
oh, could you please let me know when you correct the workflow too?

**Comment by tejalbarnwal** [comment]
Yes, it is working perfectly! Thank you so much!😊
