### ISSUE TITLE
FEATURE ADD: IDE WILL SEND INPUT TEXT SOON

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv#1634]
On detection of firmware 4.3.2 or above the IDE will now start to send text to the OpenMV Cam from the main terminal. The IDE will send the following on a key press on the main terminal:

1st USB Packet:

1 byte == __USBDBG_CMD
1 byte == __USBDBG_TX_INPUT (0x11)
4 bytes == Key-Press Data Size (usually 1 byte, might be more for UTF-8 characters)

2nd USB Packet:

Key-Press Data (usually 1 byte, might be more for UTF-8 characters)

...

The above command is issued just like script exec() so it should be easy to handle.

...

This feature must be implemented in the firmware before version 4.3.2 ships.

**Comment by iabdalkader** [comment]
I've added placeholders for the new commands, feel free to implement.
