### ISSUE TITLE
Runtime Error: Memory Allocation failed

### ISSUE THREAD

**Issue by tejalbarnwal** [openmv/openmv#1653]
**Describe the bug**
I am trying to copy a loaded image to process it. But the running of the code gives the runtime error saying that memory allocation failed. Could someone please help?

**Screenshots**
![image](https://user-images.githubusercontent.com/64950661/170997709-be5ec0a0-39a6-4d30-bb83-9c6b798fb3be.png)

**Please complete the following information**
 - IDE version: 2.9.2
 - Board: Nicla Vision
 - OS: Windows

**Comment by tejalbarnwal** [comment]
If I try to remove the `x_scale` and `y_scale` parameters from the `copy()` method, a consequent error pops up stating that the copied image is immutable. Are there any other arguments I should add to the same to get a mutable copy of the original image?
![image](https://user-images.githubusercontent.com/64950661/170998576-3c25a503-e321-42cd-a4f3-d9088bd52627.png)

**Comment by tejalbarnwal** [comment]
How do you get the frame buffer updated for a loaded image when we manipulate it?

**Comment by iabdalkader** [comment]
Try this function, with `x_scale`, `y_scale` and `copy=False`
https://docs.openmv.io/library/omv.image.html?highlight=image#image.image.Image.image.to_rgb565

Note: please post code not images of code.

**Comment by tejalbarnwal** [comment]
hey, I converted the original jpeg image to  a `.bmp` one and wrote the following code
```python
import image, sensor, pyb, time
from ulab import numpy as np

original_img = image.Image("download.bmp", copy_to_fb=True)


print("\nSize of the image:", original_img.width(), original_img.height())

cell_size = 80
numCRows = original_img.height()// cell_size
numCColumns = original_img.width()// cell_size
print("Size of circle grid:", numCRows, "X", numCColumns)

CCenterList = [(40+c*(80), 40+r*(80)) for c in range(numCColumns) for r in range(numCRows)]
print(CCenterList)

vis_img = original_img.copy(x_scale = 0.5, y_scale=0.5, copy_to_fb=True)
for c in CCenterList:
  vis_img.draw_circle(0, 0, 4, color=(0, 0, 0), thickness=10, fill=True)
```
The code runs without an error, but I don't see the image in the buffer frame getting updated. Is there a way I could visualize the manipulated image or update the buffer frame?

**Comment by tejalbarnwal** [comment]
Update: Thanks to you again, I got some part of it working, and I still had a small doubt

When I write the below code, it does update the buffer continuously
```python
import sensor, image, time
from ulab import numpy as np

while (True):
    original_img = image.Image("download.bmp", copy_to_fb=True)
    original_img.draw_circle(0, 0, 100, color = (128, 128, 128), thickness = 2, fill = True)
    time.sleep_ms(0)
```
And when I run it without a loop, it doesn't work.
```python
import image, time
from ulab import numpy as np

original_img = image.Image("download.bmp", copy_to_fb=True)
original_img.draw_circle(0, 0, 100, color = (128, 128, 128), thickness = 2, fill = True)
time.sleep_ms(20000)
```

Sorry to bother you so much, but why is it so?

**Comment by iabdalkader** [comment]
Try adding `original_img.flush()` before the sleep.

**Comment by tejalbarnwal** [comment]
Thank you so much!!
The examples in OpenMV show converting an image into a 2D Array. Is there support for other way round?

**Comment by iabdalkader** [comment]
Yes but it's going to be slow, you should check the examples that create a color palette. If you have any more questions please post them on the forums.
