### ISSUE TITLE
Failed to run OpenMV example on Arduino Nicla Vision

### ISSUE THREAD

**Issue by tejalbarnwal** [openmv/openmv#1655]
**Describe the bug**
I was trying to run the image_drawing_with_custom_palette.py from the examples in the OpenMV IDE. The script does start to execute, but in the middle of the execution, Nicla Vision gets disconnected from the IDE. All other examples under Drawing tab under examples are running fine. Its just this script. What could be the reasons for the same? I did check the USB connection, with Nicla Vision it is working fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Examples in OpenMV IDE
2. Click on OpenMV IDE &rarr; Drawing &rarr; `image_drawing_with_custom_palette.py`

The output shown:
![image](https://user-images.githubusercontent.com/64950661/171593183-9511f781-2de9-4e80-870f-c4fd676ee086.png)

Update: After I connect it again to the laptop, there is a new file in the internal storage named ERROR.LOG. It says the following:
```
FATAL ERROR:
MemManage
```
**Please complete the following information**
 - IDE version: 2.9.2
 - Firmware version: 4.3.1
 - Board: Arduino Nicla Vision
 - OS: Windows

A query regarding the same have been put up [here](https://forums.openmv.io/t/failed-to-run-openmv-example/7172) on the OpenMV Forum too

**Comment by kwagyeman** [comment]
Hi, this crashes on all cameras. Debugging now.
