### ISSUE TITLE
[bug] LCD shield y_scale=-1 not filp

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#1696]
code:
```
import sensor, image, lcd
sensor.reset() # Initialize the camera sensor.
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QQVGA2)
lcd.init() # Initialize the lcd screen.

while(True):
    lcd.display(sensor.snapshot(), y_scale=-1) 
```

The document says that if the y_scale is negative, it will be flipped, but the LCD shield is not flipped.

x_scale=-1 works fine.

**Comment by iabdalkader** [comment]
@kwagyeman Is this related to the scaling bug ?

**Comment by kwagyeman** [comment]
No, this was ROI related.

**Comment by iabdalkader** [comment]
I mean is it fixed by the recently merged patch ?

**Comment by kwagyeman** [comment]
Unsure, probably not. I can add this to fix right now.

**Comment by kwagyeman** [comment]
Unsure, probably not. I can add this to fix right now.

**Comment by kwagyeman** [comment]
Hi, this can't be fixed without turning triple buffering on.

Draw image works by processing the image from the top left to bottom right. When you specify the image to be flipped it just outputs the pixels that it's processing from bottom to top versus top to bottom. However, when the LCD shield is used without triple buffering there's no display buffer so the bottom to top lines are just sent to the LCD immediately which just displays them top to bottom.

I'll add a error note if you try to do this without triple buffering on.

(Making draw image process the image top to bottom when y_scaled is -1 would require writing the whole piece of code).

**Comment by kwagyeman** [comment]
https://github.com/openmv/openmv/issues/1696
