### ISSUE TITLE
Update firmware with latest version of ulab

### ISSUE THREAD

**Issue by tejalbarnwal** [openmv/openmv#1697]
[Here](https://forums.openmv.io/t/ulab-numpy-dimensions/7339) is the link to the issue on the OpenMV forum that I was facing concerning the implementation of more than two dimensions of NumPy arrays.
The author for `ulab` just stated that this bug was fixed recently. This could be found [here](https://github.com/v923z/micropython-ulab/issues/498#issuecomment-1194283767)

It would be really helpful if the parameter for `ULAB_MAX_DIMS` could be set to 4 instead of 2 to be used on OpenMV products. 

**Please complete the following information**
 - IDE version: [2.9.2]
 - Firmware version: [4.3.1]
 - Board: [Arduino Nicla Vision]
 - OS: [e.g. Windows]

**Comment by iabdalkader** [comment]
Don't you mean 3 instead of 2 ? Why do you need a 4D array ?

**Comment by iabdalkader** [comment]
This adds about 20KBs to the firmware image, so there must be a very good reason to enable 3D arrays.

**Comment by tejalbarnwal** [comment]
I needed 3D arrays to convert RGB images to NumPy arrays

**Comment by tejalbarnwal** [comment]
Hey, new functionality was added to the ulab as found [here](https://github.com/v923z/micropython-ulab/issues/527). Could these be added to the firmware of the board that I am using. How can I do so?

**Comment by iabdalkader** [comment]
This issue has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/ulab-numpy-dimensions/7339/4

**Comment by tejalbarnwal** [comment]
Hey, I have a very dumb doubt, updating the firmware with modifications corresponding to `ulab` would allow me to use new functions in OpenMV IDE too, right?

**Comment by iabdalkader** [comment]
Yes.

**Comment by tejalbarnwal** [comment]
Great, thank you so much!
Am sorry to write it here, I will edit this comment later but this is the only medium I can talk to you. Could you please https://forums.openmv.io/t/find-displacement-with-usb-vcp/7349 at this issue too? I will be really grateful to you for this!

**Comment by tejalbarnwal** [comment]
> To update ulab you'll have to update the submodule here omv/modules/ulab, google how to do that or just replace it with a newer ulab and rebuild.
Hey, I followed the following steps to update the submodule
```bash
cd omv/modules/ulab
# this is the branch I want 
git checkout nonzero
# Update
git pull
```
And then committed to changes to the forked repository, but there seems to error in building the firmware for all the boards except OPENMV2
![image](https://user-images.githubusercontent.com/64950661/181815931-cb64e34d-eb5f-4c5d-90d4-c9e6ba5dc7be.png)

All the boards except OPENMV2 give the same error regarding ` undefined reference to io_load_obj, io_loadtxt_obj, io_save_obj, io_savetxt_obj `. @iabdalkader Any idea what am I missing?

**Comment by tejalbarnwal** [comment]
Hey, I solved it
Thanks to @v923z

**Comment by iabdalkader** [comment]
Good, I'll update ulab soon.

**Comment by iabdalkader** [comment]
@v923z Any plans for a new stable release soon or a tag after https://github.com/v923z/micropython-ulab/commit/00139bdd9684bd9d10b0d89fa8fbb0906f2d05af please ?

**Comment by v923z** [comment]
@iabdalkader There is a pending issue that might possibly affect you, too. As soon as that is fixed (should happen tomorrow, or the day after tomorrow), I'll issue a new tag.
