### ISSUE TITLE
When will the firmware supporting the pro version be released?

### ISSUE THREAD

**Issue by jiskra** [openmv/openmv#1699]
Dear author, I see that there is already a pro version in the hardware design. Although the design has not been completed, I see the main change points. Added some peripherals to the board, modified the USB port to typeC, and added TVS protection. I would like to know when the firmware will be supported, thank you.

**Comment by iabdalkader** [comment]
I'm working on it, will push it upstream soon.

**Comment by iabdalkader** [comment]
This was added a while ago.
