### ISSUE TITLE
Arduino Nicla Vision micro_speech audio_callback method OSError

### ISSUE THREAD

**Issue by kisdia** [openmv/openmv#1756]
**Describe the bug**
When using micro_speech on Arduino Nicla Vision board the audio_callback function fails with "OSError: Audio data size too small!" message.

**To Reproduce**
Steps to reproduce the behaviour:
1. load micro_speech example
2. make sure to add pre-trained model to board memory
3. run example
4. fails on line 13 audio.start_streaming(speech.audio_callback)
5. pop-up error message "OSError: Audio data size too small!"

**Expected behavior**
audio_callback working on Arduino Nicla vision the same way as other boards

**Screenshots**

**Please complete the following information**
 - IDE version: 2.9.7
 - Firmware version: 4.3.2
 - Board: NICLAV
 - OS: Windows

**Comment by iabdalkader** [comment]
Thanks for reporting this issue, MicroSpeech has never been tested on Nicla Vision, but now it should be working. You can try loading the development firmware if you want the fix now, or wait until the next stable release is out.
