### ISSUE TITLE
MT9V0XX sensor clock frequency to high on Portenta H7

### ISSUE THREAD

**Issue by j-wagner-md** [openmv/openmv#1776]
On the Portenta H7 board the configured sensor clock frequency for the MT9V034 global shutter module (**26.6 Mhz**) is not working properly.  
Measuring it externally with an oscilloscope we see **close to 28.6 MHz**
![image](https://user-images.githubusercontent.com/85220117/216979357-002346e6-b780-4a42-aaf6-095fb978261e.png)

The datasheet for the MT9V034 global shutter sensor specifies a maximum input clock frequency of 27.0 MHz.
![image](https://user-images.githubusercontent.com/85220117/216980553-6ec10126-b49d-400e-a5ae-72078d0db96f.png)

**So the sensor will be used outside its specified limits.**

Attempts to change the sensor frequency to 27MHz or 26MHz were not successful and the sensor still showed the 28.6MHz system clock frequency (`src/omv/sensors/mt9v0xx.h` --> `MT9V0XX_XCLK_FREQ`).
Despite the Portenta having two oscillators on board. One with 25Mhz output and one with 27MHz.
![image](https://user-images.githubusercontent.com/85220117/216982266-694a8c2c-30fa-454d-b1e4-8bcbb884b4e6.png)

Only setting it to **25MHz** showed the desired results of lowering the frequency into the specified frequency range (It measured 25MHz as expected)

**Setup information**
 - Firmware version: 4.4.1
 - Board: Portenta H7 Lite
 - Sensor: MT9V034 - OpenMV global shutter module

---
As a note:

Mounting the same sensor onto an OpenMV Cam H7 Plus with the same firmware hash (set with 26.6 MHz before the test changes) resulted in exact Clock speeds:
![image](https://user-images.githubusercontent.com/85220117/216983138-7fab8bc2-5766-4168-ae63-48a8193f7baa.png)

**Comment by iabdalkader** [comment]
The Portenta has different OSC frequency and different PLL settings, it's probably not possible to get an exact 26.6MHz or 27MHz. As far as I know there aren't any working kits out there with the MT and the Portenta, that's why it hasn't been a priority to test/fix this, but maybe that has changed. I'll send a fix later to override the frequency for Portenta to 25MHz to keep it on the safe side.

**Comment by j-wagner-md** [comment]
Thank you @iabdalkader for your fast support :+1:
