### ISSUE TITLE
Camera module support

### ISSUE THREAD

**Issue by Bexin3** [openmv/openmv#1792]
Hi, sorry for creating an issue, I couldn't find a discussion place. Can any mini camera sensors be used, or does it have to be one of the listed ones, and in case it have to be the listed ones, do they have to be from openmv? as shipping is an issue for me. I want to use the sensor with a Portenta board

**Comment by kwagyeman** [comment]
Please ask questions on the forum: https://forums.openmv.io/

As for sensor support. We have a specific driver per sensor. You can't just use any sensor.

**Comment by Bexin3** [comment]
Thank you. Which lcd displays are supported?
