### ISSUE TITLE
get_threshold function result is incorrect 

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#1794]
a_value and b_value result is incorrect .

```
import sensor, image, time

sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.skip_frames(time = 2000)

clock = time.clock()

while(True):
    img = sensor.snapshot()
    histogram = img.get_histogram()
    THRESHOLD = histogram.get_threshold()
    l  = THRESHOLD.l_value()
    a = THRESHOLD.a_value()
    b = THRESHOLD.b_value()
    print(THRESHOLD)
    img.binary([(0, l), (-128, a),(-128, b)])
```

**Expected behavior**
IDE show binary image with optimal thread. 

**Screenshots**
![1677758438(1)](https://user-images.githubusercontent.com/9582040/222423000-46cfff26-de3a-4dac-87b7-d04c1880638f.png)

**Please complete the following information**
 - IDE version: 2.9.7
 - Firmware version: 4.3.3
 - Board: OpenMV4 Plus
 - OS: Windows

**Comment by kwagyeman** [comment]
What output were you expecting? The method just finds a nice split value to threshold the image.

**Comment by kwagyeman** [comment]
Hi, this is because you are passing the arguments to binary incorrectly. It's a list of 6 value tuples. Or a list of 2 value tuples.

```
import sensor, image, time

sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.skip_frames(time = 2000)

clock = time.clock()

while(True):
    img = sensor.snapshot()
    histogram = img.get_histogram()
    THRESHOLD = histogram.get_threshold()
    l  = THRESHOLD.l_value()
    a = THRESHOLD.a_value()
    b = THRESHOLD.b_value()
    print(THRESHOLD)
    img.binary([(0, l, -128, a, -128, b)])
```

However, I also found an issue with get_threshold. A/B arguments were not shifted. 

https://github.com/openmv/openmv/pull/2074
