### ISSUE TITLE
find_rect can't find big rect 

### ISSUE THREAD

**Issue by tonyzhangnxp** [openmv/openmv#1796]
**Describe the bug**
Can not find the rect while the rect almost fill the whole picture.
but it works in old version v1.12.

**To Reproduce**
use bellow test image:
![find_rect_test](https://user-images.githubusercontent.com/76503812/223012209-1be377e8-28c3-4528-b96f-68f504bba616.png)

**Expected behavior**
result should be :
![1678073497(1)](https://user-images.githubusercontent.com/76503812/223013868-f64aa887-d136-43dc-8e17-8f932d3e0f99.png)

**Please complete the following information**
 - IDE version: 2.9.2
 - Firmware version: latest

**fix tryings**
use yuv_tab converting rgb565 to gray, it works fine.
code changes in fixing.txt

**Comment by kwagyeman** [comment]
Hi, I just tested with the latest firmware and it appears to be working.

If you'd like me to investigate more can you provide a static image that fails and the code you were using.

I tried the code on the H7 Plus, on the H7 regular it may not work due to memory limits.
