### ISSUE TITLE
VL53l1X library + Openmv cam h7 plus

### ISSUE THREAD

**Issue by gabrielcrivat** [openmv/openmv#1800]
**Describe the bug**
Using this ToF sensor with the camera I can retrive the distance.
BUT, I want the get the roi of the sensor and to set it. Looking at the library vl53l1x.py it is mentioned SetRoi() at lines 90 - 91.
I'm new in this subject
How can I use the library to manage the ROI? Can you please write me the steps to do?
I would have expected to see the all the methods defined.
Thanks in advance!

**Please complete the following information**
 - IDE version: 2.9.7
 - Firmware version: 4.4.2
 - Board: OPENMV-H7 PLUS + VL53l1 satel
 - OS: Windows 10

**Comment by kwagyeman** [comment]
Hi, the python code is implemented based on what the C driver code from here does to setup the sensor over I2C: https://www.st.com/en/embedded-software/stsw-img007.html

So, there's no set_roi in our driver. You need to look at the C library (above) and see what it's doing.
