### ISSUE TITLE
Refactor JPEG code.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv#1803]
`jpeg.c` is basically for ST so it should be split into:

* Software JPEG -> imlib/jpeg_enc/dec.c
* Hardware JPEG -> `ports/stm32/jpeg_enc/dec.c` 

Hardware JPEG decoder support is basically ready here https://github.com/openmv/openmv/pull/1604 it doesn't have to be enabled by default but should be merged .

Common JPEG code can be duplicated, but of course it would be better if some things are shared, for example tables in `imlib/jpeg_tab.c` etc...

**Comment by kwagyeman** [comment]
Executing this.
