### ISSUE TITLE
MLX90640 scale function error

### ISSUE THREAD

**Issue by joshpearse** [openmv/openmv#1805]
### Steps to reproduce
1. Run code below:

```
import sensor, image, time, fir

drawing_hint = image.BICUBIC

fir.init(type = fir.FIR_MLX90640) #P4 to SCL and P5 to SDA

w = fir.width() * 10
h = fir.height() * 10

clock = time.clock()

while(True):
  clock.tick()
  
  try:
      img = fir.snapshot(x_size = w, y_size = h, color_palette = sensor.PALETTE_IRONBOW, hint = drawing_hint, copy_to_fb = True, hmirror = False, vflip  = True, scale = [35, 40], pixformat=fir.GRAYSCALE)
      img.negate()
      
      img.compress(quality = 70)
  
  except OSError:
      continue
  
  print(clock.fps())
```

### Expected behaviour
Grayscale output like with FLIR lepton. In this case temperatures are below 35C so should be a black screen

### Actual behaviour
All pixel values are 130

See https://forums.openmv.io/t/mlx90640-scale-function/8041 

### Describe your setup

**IDE version:** 2.9.7

**Firmware version:** 4.4.1

**Operating system:** Windows 10 on bootcamp

**Comment by kwagyeman** [comment]
Hi, there's no bug. You are just asking the algorithm to do something that doesn't make sense.

```
img = fir.snapshot(x_size = w, y_size = h,
            color_palette = None,
            hint = drawing_hint, copy_to_fb = True,
            hmirror = False, vflip  = True,
            scale = [35, 40], pixformat=fir.GRAYSCALE)
```

Does what you want. Note that the IRON BOW color palette has gray/white as it's 0 zero.

**Comment by iabdalkader** [comment]
This issue has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/mlx90640-scale-function/8041/7
