### ISSUE TITLE
bug with to_grayscale(copy = True)

### ISSUE THREAD

**Issue by jcmag** [openmv/openmv#1811]
**Describe the bug**
I want to detect white lines in my camera’s images, using this code:

```
img = sensor.snapshot()
blackImage = img.to_grayscale(copy = True).binary([(190, 255)])
segments = blackImage.find_line_segments(merge_distance = 10, max_theta_diff = 5)    
for segment in segments:
    img.draw_line(segment.line(), color = (255, 0, 0))
```

I’m calling to_grayscale() and binary() to detect the lines in a black and white image, to be more accurate.
But the last call (img.draw_line) doesn’t draw the lines in the displayed image (in the IDE).

If I put to_grayscale(copy = False), I see grey lines in the displayed image (the grey one).

And same issue with:
```
black_img = img.to_grayscale(copy = True)
black_img.binary([(190, 255)])
```

**Expected behavior**

I expect the lines to be drawn and displayed in the colored image.

**Comment by kwagyeman** [comment]
Found the bug.  Very simple issue.

**Comment by kwagyeman** [comment]
https://github.com/openmv/openmv/pull/1813

**Comment by iabdalkader** [comment]
This issue has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/white-lines-detection/8135/6
