### ISSUE TITLE
Replacing mt9v034c12stm with stc #question#

### ISSUE THREAD

**Issue by cyhcyhgo** [openmv/openmv#1825]
**Replacing mt9v034c12stm with stc**
The mt9v034 camera can only output mono images. Can I replace it with mt9v034c12stc so it can output colorful images?

**Comment by kwagyeman** [comment]
Hi, I just proved this for a customer and added a feature that gives you color output. So, yes.

**Comment by cyhcyhgo** [comment]
> Hi, I just proved this for a customer and added a feature that gives you color output. So, yes.

Thank you very much for solving my problem！
