### ISSUE TITLE
Unable to compile micropython

### ISSUE THREAD

**Issue by Barbocchio** [openmv/openmv#1841]
Hi, I downloaded the source and tried to compile it, but in some way it reports this error:

CC ../py/warning.c
../py/stackctrl.c: In function ‘mp_stack_ctrl_init’:
../py/stackctrl.c:32:32: error: storing the address of local variable ‘stack_dummy’ in ‘mp_state_ctx.thread.stack_top’ [-Werror=dangling-pointer=]
   32 |     MP_STATE_THREAD(stack_top) = (char *)&stack_dummy;
../py/stackctrl.c:31:18: note: ‘stack_dummy’ declared here
   31 |     volatile int stack_dummy;
      |                  ^~~~~~~~~~~
In file included from ../py/runtime.h:29,
                 from ../py/stackctrl.c:27:
../py/mpstate.h:323:23: note: ‘mp_state_ctx’ declared here
  323 | extern mp_state_ctx_t mp_state_ctx;
      |                       ^~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [../py/mkrules.mk:80: build/py/stackctrl.o] Error 1
make: *** Attesa per i processi non terminati....
make: uscita dalla directory «/home/davide/openmv/src/micropython/mpy-cross»

### Steps to reproduce
1. follow the instructions in the readme for building from source
2. cd openmv/src/micropython/mpy-cross
3. make -j${nproc}

### Expected behaviour
It should compile just fine, I didn't change a bit in the code, I even tried to clone micropython's official repo and that compiled as expected, so it looks to be an issue only in this branch

### Describe your setup

**Firmware version:**
I cloned the latest release to date 2023/05/12 

**Operating system:**
Arch Linux

**Comment by iabdalkader** [comment]
Our MicroPython fork is not meant to be built standalone, we make changes to the build files and other files so it won't build. If you wanted to build MicroPython you should build the upstream one, if you want to build our firmware follow this guide:

https://github.com/openmv/openmv/blob/master/src/README.md

**Comment by Barbocchio** [comment]
Yeah I followed that guide, however I got that error; I did the exact same steps 
"
To build the firmware, run the following commands inside the openmv repository:

cd openmv
make -j$(nproc) -C src/micropython/mpy-cross   # Builds Micropython mpy cross-compiler
make -j$(nproc) TARGET=<TRAGET_NAME> -C src    # Builds the OpenMV firmware
"
