### ISSUE TITLE
VS23S010 on TV shield

### ISSUE THREAD

**Issue by cyhcyhgo** [openmv/openmv#1845]
This chip is so rare that I can't buy it in any online mall except the official website. Is there a chip that can replace it?

**Comment by kwagyeman** [comment]
Hi, you should ask @kidswong999 about this. They build that shield. Not sure how they get access to it.

As for another chip that does NTSC. I don't know. MCUs can honestly generate it if they have a DAC onboard that can run at a high enough frequency (that's the problem though, you need 10's MHz update rate which most MCU DACs can't do).
