### ISSUE TITLE
Using DFU to updating the firmware

### ISSUE THREAD

**Issue by 846354866** [openmv/openmv#185]
Hi, I use OpenMV Cam to update the firmware, OpenMV Cam can run, but I use the same method to update the firmware to the M7 kernel board (stm32f767zi) can not run.
make[1]: Leaving directory `/home/ouki/openmv/src/bootloader'
   text	   data	    bss	    dec	    hex	filename
  14280	    212	  10560	  25052	   61dc	/home/ouki/openmv/src/../firmware/OPENMV3/bootloader.elf
   text	   data	    bss	    dec	    hex	filename
 945772	    116	 130592	1076480	 106d00	/home/ouki/openmv/src/../firmware/OPENMV3/firmware.elf
ouki@ubuntu:~/openmv/src$ make flash_dfu
Mass erase...
File: /home/ouki/openmv/src/../firmware/OPENMV3/openmv.dfu
    DfuSe v1, image size: 1077261, targets: 1
    Target 0, alt setting: 0, name: "ST...", size: 1076976, elements: 2
      0, address: 0x08000000, size: 131072
      1, address: 0x08020000, size: 945888
    usb: 0483:df11, device: 0x0000, dfu: 0x011a, UFD, 16, 0xe36a4bba
Writing memory...
0x08000000  131072 [=========================] 100% 
0x08020000  945888 [=========================] 100% 
Exiting DFU...

**Comment by iabdalkader** [comment]
The firmware only supports our cams, it can be modified to work on other boards.
