### ISSUE TITLE
Update all simple math methods with draw_image backend support

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv#1855]
All the logical functions and etc. haven't been updated to be flexible yet using draw_image support and require you match the pixel formats right now to work. This results in them being hard to use.

**Comment by iabdalkader** [comment]
This issue has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/how-to-mask-the-frame-buffer/8387/5
