### ISSUE TITLE
Memory leak when using urequests on Nicla vision

### ISSUE THREAD

**Issue by hannesrichter** [openmv/openmv#1895]
**Describe the bug**
I found a memory leak when using the included version of urequets. The sixth request in row always fails with "ENOMEM". To prevent this from happening, I would like to free up the resources by calling "close()" on the Response-object, but the version of urequests provided does not implement this function. 

**To Reproduce**
- run any six (successful) get-requests on the arduino nicla vision
- it does not matter if the request is called in a loop or by interrupt.

**Expected behavior**
Either have no need to free allocated memory or implement some function to have the user clean up after use.
Like it is done [here](https://github.com/micropython/micropython-lib/blob/7128d423c2e7c0309ac17a1e6ba873b909b24fcc/python-ecosys/urequests/urequests.py#L10C9-L10C9)

**Workaround**
a quick workaround is using the original code from [here](https://github.com/micropython/micropython-lib/blob/master/python-ecosys/urequests/urequests.py)

**Please complete the following information**
 - IDE version: 3.0.3
 - Firmware version: 4.4.2
 - Board: Arduino Nicla Vision
 - OS: Windows 11

**Comment by kwagyeman** [comment]
Hi, yes, this library doesn't have the robust sockets implementation like on the RSTP code.

Could you send a pull request for this with the cleanup included? 

This script uses sockets correctly: https://github.com/openmv/openmv/blob/master/scripts/libraries/rtsp.py
