### ISSUE TITLE
STM32F765VIT6 or STM32F765VGT6

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#191]
Hello, I saw the OpenMV-M7 with 2M flash, but the pictures and schematic are both STM32F765VGT6 with 1M flash. 
So it is STM32F765VIT6 or STM32F765VGT6?
^_^

**Comment by iabdalkader** [comment]
Hi, they're both pin-compatible so we can decide when ordering, but we're going to use the 2MBs version.
