### ISSUE TITLE
at removable disk(E:) the main.py, readme and openmv_disk file is presented . I tried openmv ide software and clicked to run it showing Run time error: sensor control failed. how to solve this problem? using open mv cam h7 plus

### ISSUE THREAD

**Issue by bsri672** [openmv/openmv#1927]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information**
 - IDE version: [e.g. 2.6.8]
 - Firmware version: [e.g. 3.8.0]
 - Board: [e.g. OPENMV-H7+/Portenta]
 - OS: [e.g. Windows/Linux/iOs]

**Comment by bsri672** [comment]
at removable disk(E:) the main.py, readme and openmv_disk file is presented . I tried openmv ide software and clicked to run it showing Run time error: sensor control failed. how to solve this problem? using open mv cam h7 plus

**Comment by kwagyeman** [comment]
Hi, is the sensor secure on the camera unit? That error happens when we are not able to initialize the sensor module.

**Comment by bsri672** [comment]
How to initialize the sensor module. lepton 3.5 openmv h7 plus camera?

**Comment by kwagyeman** [comment]
It should just work if you are using the flir lepton adapter.

**Comment by bsri672** [comment]
how to solve this error ? sensor control failed: runtime error

**Comment by bsri672** [comment]
how to mount internal drive files. in E drive only main.py, readme, and openmv_disk is there but if i click on run it is not running.

**Comment by iabdalkader** [comment]
Hi, please use the forums to ask any questions you have https://forums.openmv.io/
