### ISSUE TITLE
how to mount internal drive files. in E drive only main.py, readme, and openmv_disk is there but if i click on run it is not running. ide version:4.0.1, firmware version: 4.4.3, board: openmv cam h7 plus stm32h743 w/sdram os:windows

### ISSUE THREAD

**Issue by bsri672** [openmv/openmv#1929]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information**
 - IDE version: [e.g. 2.6.8]
 - Firmware version: [e.g. 3.8.0]
 - Board: [e.g. OPENMV-H7+/Portenta]
 - OS: [e.g. Windows/Linux/iOs]

**Comment by bsri672** [comment]
how to mount internal drive files. in E drive only main.py, readme, and openmv_disk is there but if i click on run it is not running. ide version:4.0.1, firmware version: 4.4.3, board: openmv cam h7 plus stm32h743 w/sdram os:windows

**Comment by iabdalkader** [comment]
Hi, please use the forums to ask any questions you have https://forums.openmv.io/
