### ISSUE TITLE
ImportError: no module named 'lcd' in firmware 4.5.0

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#1988]
hardware: OpenMV4 H7 Plus
firmware: 4.5.0

code:
```
import sensor, image, time
import lcd

sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.skip_frames(time = 2000)

clock = time.clock()

while(True):
    clock.tick()
    img = sensor.snapshot()
    print(clock.fps())
```

I guess the lcd module was deleted. Could you fix it ?

**Comment by iabdalkader** [comment]
No I refactored the display module and the API has changed, it's now called `Display` see the updated examples and the docs here: https://docs.openmv.io/library/omv.display.html#module-display
