### ISSUE TITLE
does sensor.set_auto_exposure work?

### ISSUE THREAD

**Issue by TronePans** [openmv/openmv#204]
I bought a Cam4 module, it works well indoor, but when outdoor, the pixel value of bright area may reach to  255 in gray level. And I could not find information about the value which is required in sensor.set_auto_exposure(Ture, value=?). I tried some value randomly, but it made no sense, could anyone tell me why?

**Comment by iabdalkader** [comment]
Yes it's [implemented](https://github.com/openmv/openmv/blob/master/src/omv/ov7725.c#L341) but it doesn't work unless you also disable the auto gain, try this:
```
sensor.set_auto_gain(False, value=100)
sensor.set_auto_exposure(False, value=400)
```
Note the exposure value is 16 bits.

If you want to find a sane value for some register you should leave auto functions enabled, skip some frames and then read that value, example:

```
sensor.skip_frames(30)
print(sensor.__read_reg(0x08))
```
