### ISSUE TITLE
HID mode doesn't work after new firmware update

### ISSUE THREAD

**Issue by Igino95** [openmv/openmv#2049]
Hello, 

i'm working with Arduino nicla vision, openMV IDE 4.1.1 on windows. Frome serial terminal after connection: 
OpenMV 5f9fe8b; MicroPython b0b6a67; NICLAVISION-STM32H747

After connecting the board to the PC via USB cable, the open MV IDE told me to update the firmware, I did it and now the HID mode no longer works.

I also tried resetting the board and loading the example file, also creating the boot.py file like this:

import pyb
pyb.usb_mode('VCP+HID') # serial device + mouse (UNCOMMENT THIS LINE!)

and saving this script as main.py:

import pyb
import time

hid = pyb.USB_HID()

while True:
     # x, y and scroll
     # move 10 pixels to the right
     hid.send((0, 10, 0, 0))
     time.sleep_ms(500)

but the board keeps crashing and restarting

Can you help me? do you have the old firmware?

Thank you

**Comment by kwagyeman** [comment]
The boot process was changed around in the latest firmware update. @iabdalkader will know more about this.

The old firmware is here: https://github.com/openmv/openmv/releases/tag/v4.5.0

**Comment by Igino95** [comment]
Ah ok, will it be available again?

In any case the old version works, thank you.

**Comment by iabdalkader** [comment]
>> Ah ok, will it be available again?

I will try to make it work again.

**Comment by Igino95** [comment]
Ok thank you

**Comment by iabdalkader** [comment]
The only way to fix this is to move boot.py before the USB device is initialized, does this break anything for you @kwagyeman ?

Alternatively, this in `boot.py` (or `main.py`) works too:

```Python
import pyb

if pyb.usb_mode() == "VCP+MSC":
    pyb.usb_mode(None)
    pyb.usb_mode("VCP+HID")
```

**Comment by kwagyeman** [comment]
It's not change the boot order.

I think the fix you mentioned in code is enough.

Thanks! :)

**Comment by Igino95** [comment]
Ok, thank you for support! :)
