### ISSUE TITLE
Upload OPEMMV3 dfu to my openmv with stm32f7 

### ISSUE THREAD

**Issue by SSSnow** [openmv/openmv#209]
hello ,
on terminal  key "cd openmv/usr" ,then ''python openmv-ide.py" ,click the connect button, warning"Firmware version mismatch! Please update the firmware image and/or the IDE!"
i update the firmware , but it doesn't work still.
could you help me?

**Comment by iabdalkader** [comment]
Hi, openmv-ide.py is the old GTK IDE it's not maintained anymore, I keep it around for testing, you should use the QT IDE instead, download from [openmv.io](https://openmv.io/pages/download)
