### ISSUE TITLE
firmware for stm32f765vgt6

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#210]
Hello,

I have trouble with firmware at stm32f765vgt6.

The firmware is OK at stm32f765**vit6**, but it can't run at stm32f765**vgt6**.

Maybe the flash layout is different, and how to solve it?

Thank you!

**Comment by iabdalkader** [comment]
The VGT6 has 1MB flash, the firmware needs more flash, it won't work without disabling some functions.

**Comment by kidswong999** [comment]
Could you send me a firmware that you tested on VGT6?
Thanks
