### ISSUE TITLE
i2c in OpenMV3

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#212]
I connected PCA9685 servo module to openmv, and I found a bug.
i2c in OpenMV2:
```
>>>from pyb import I2C
>>>i2c = I2C(2, I2C.MASTER)
>>>i2c.scan()
[64, 112]
>>>i2c.mem_read(1,64,1)
b'\x04'
>>> i2c.mem_read(1,64,0)
b'\x11'
```
i2c in OpenMV3:
```
>>>from pyb import I2C
>>>i2c = I2C(2, I2C.MASTER)
>>>i2c = I2C(2, I2C.MASTER)
>>>i2c.scan()
[64, 112]
>>> i2c.mem_read(1,64,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: 116
>>> i2c.mem_read(1,64,0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: 116
```

Is there an issue in the firmware?

**Comment by zz2633105** [comment]
I have also encountered the same problem

**Comment by iabdalkader** [comment]
Hi, I don't have that module, but I'll test I2C and get back to you.

**Comment by zz2633105** [comment]
Hey, did the test results come out?

**Comment by kwagyeman** [comment]
Hi, please post issues to the forum. As for the above problem. Try using the non-memory commands. Like i2c.send() and i2c.recv(). I have some good example scripts on how to use I2C packaged with the IDE. Checkout the Pixy emulation scripts in particular. Also, you need to have pull-up wires on the I2C lines.

**Comment by iabdalkader** [comment]
@zz2633105 @kidswong999 Please let me know if the issue was missing resistors if not I'll debug the code.

**Comment by zz2633105** [comment]
@iabdalkader I do not know if the lack of resistance, but the same operation, OpenMV2 can run, OpenMV can not. This is why?
![pca9685](https://cloud.githubusercontent.com/assets/27983832/25510576/bf315fe8-2bf3-11e7-9cdb-cbb59cafae18.png)

**Comment by zz2633105** [comment]
@iabdalkader PCA9685模块有上拉电阻

**Comment by iabdalkader** [comment]
I think you need pull-ups, I don't see any resistors on that board. Do you have a link/pic of the PCA board ?

**Comment by zz2633105** [comment]
@iabdalkader The PCA9685 module has a pull-up resistor

**Comment by iabdalkader** [comment]
You should try this [library](https://github.com/adafruit/micropython-adafruit-pca9685/blob/master/pca9685.py) and import i2c from machine not pyb, as suggested in the forums.

**Comment by zz2633105** [comment]
@iabdalkader alright, thank you very much

**Comment by kidswong999** [comment]
Hello, I am using machine instead of pyb, and it works. 
Thanks. : )

**Comment by kidswong999** [comment]
I upload code and tutorial at http://openmv.cc/doku.php?id=tutorial:7
I will be uploaded to the forum recently.
[openmv-pca9685.zip](https://github.com/openmv/openmv/files/963384/openmv-pca9685.zip)

**Comment by iabdalkader** [comment]
@kidswong999 Hey would you be interested in re-writing those tutorials in English ?  We're looking for someone to help with tutorials. If you're interested contact me at iabdalkader at openmv.io
