### ISSUE TITLE
Fir snapshot color_palette problems with new firmware > 4.5.0 . 

### ISSUE THREAD

**Issue by amitai-debiche** [openmv/openmv#2167]
**Description**
Updated OpenMV PureThermal firmware to version 4.5.2, was previously on version 4.5.0. The following code no longer works and produces a TypeError: extra keyword argument given:

try:
        img = fir.snapshot(
            x_size=w,
            y_size=h,
            hint=image.BICUBIC,
            # ERROR BELOW
            color_palette=image.PALETTE_IRONBOW,
            pixformat=image.GRAYSCALE,
            copy_to_fb=True
        )
    except OSError:
        continue

I've tried using fir.PALETTE_IRONBOW, as well as sensor.PALETTE_IRONBOW. None of them worked, this also means the main.py code that shipped with the board now no longer functions as the following code produces an error:

 img.draw_image(fir_img, 0, 0, x_scale = x_scale, y_scale = y_scale,
                       color_palette = sensor.PALETTE_IRONBOW,
                       alpha_palette = alpha_pal,
                       hint = image.BICUBIC)

The above code had no issues prior to 4.5.1, both 4.5.2 and 4.5.1 produce the error.

**To Reproduce**
1. Try to run code, with FIR sensor to change color palette
2. See error

**Expected behavior**
I expect the program to compile, and correctly use the color_palette designated in the code. 

**Please complete the following information**
 - IDE version: 4.1.5
 - Firmware version: 4.5.2
 - Board: OPENMV PureThermal
 - OS: macOS

I'm more than happy to add screenshots of the code working in prior firmware versions, if that would be helpful? Thank you!

**Comment by kwagyeman** [comment]
Hi, please update to the latest dev release firmware. See tools->Install Latest Development Release.

Then the new main.py script is here: https://github.com/openmv/openmv/blob/master/scripts/examples/50-OpenMV-Boards/51-Pure-Thermal/00-HelloWorld/pure_thermal.py
