### ISSUE TITLE
With v4.5.3 RPC SPI no longer works 

### ISSUE THREAD

**Issue by Sommjo11** [openmv/openmv#2173]
I have an application that uses my H7 plus as an rpc SPI slave. Was working with older firmware releases (I.e. v4.5.2 and v4.2.3) but with v4.5.3 no longer works.

Implementation is similar to the example „popular_features_as_the_remote_device“

Spi master is an Arduino based controller using the OpenMV Arduino RPC library version 1.0.9.

**Comment by kwagyeman** [comment]
Hi, I found the issue. Was just a pin control problem. Fixed it in a PR. Will post a firmware to your forum thread.

**Comment by kwagyeman** [comment]
Tracking: https://forums.openmv.io/t/upgrade-to-v4-5-3-rpc-spi-no-longer-working/9306
