### ISSUE TITLE
Can this support PyTorch or JAX models?

### ISSUE THREAD

**Issue by wcoder8** [openmv/openmv#2181]
Supporting tensorflow models is nice, but in the current year PyTorch is what most researchers and ML practitioners want to use. PyTorch support would be important. Also Google will likely officially deprecate Tensorflow at some point. They are already working on their next framework called JAX. (maybe that could be added next)

**Comment by kwagyeman** [comment]
Hi, it's not really something we need to do. We're shifting to products with CNN accelerators in the future. These all have their own model ingestion systems on the PC side which create a model for the CNN accelerator on the system. As such, it's not a problem we have to solve.
