### ISSUE TITLE
OpenMV RT cannot connect to USB after first booting via 3V3 Vin.

### ISSUE THREAD

**Issue by antonvh** [openmv/openmv#2196]
**Describe the bug**
OpenMV IDE shows 'No OpenMV Cams Found!' if I connect my OpenMV RT to USB after first booting via 3V3 Vin.

Full project here. Scroll down to troubleshooting section.
https://www.antonsmindstorms.com/2024/04/06/robot-ball-kicker-project-building-a-lego-spike-prime-robot-with-openmv-vision/

**To Reproduce**
1. Boot Cam via 3v3 Vin
2. Click on 'Connect (cmd-E)'
3. See error

**Expected behavior**
Always connect. I used a H7 in the exact same setup, with the same scripts, and had no problems connecting.
First connecting to USB and the Vin also solves the issue.

**Please complete the following information**
 - IDE version: 4.1.3
 - Firmware version: OpenMV v4.5.3; MicroPython v1.22-omv.r17; OpenMV IMXRT1060-MIMXRT1062DVJ6A
 - Board: OpenMV RT
 - OS: Mac

![20240414_131244](https://github.com/openmv/openmv/assets/355996/81798191-cdf8-4748-a41d-e80cd35cb71f)

**Comment by iabdalkader** [comment]
This issue has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/usb-c-no-openmv-cam-found-on-openmv-rt-after-booting-with-3v3/9428/3

**Comment by kwagyeman** [comment]
Hi, I explain the solution on the forums. Forcing 3.3V into the system bypasses it's power concept. However, it will still work.

You'll need to fiddle with the power button though. The processor does not like the 3.3V rail turning on before it's battery backup rail.
