### ISSUE TITLE
Corrupt Lines

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv#2216]
When the number of frame buffers is set to 1 on the RT1062 you'll get those corrupt cache invalidation lines on small resolutions like QQVGA. That said, unlike before, it's only one line near the top left of the frame. Not all over it. So, it's a small race condition somewhere. Most likely has to do with the eDMA capture potentially falling behind. The code doesn't wait for it to finish before releasing the frame right now. Probably need to add some code to wait on it finishing.

It doesn't seem to bother multiple buffer mode, which everyone uses. But, something to eventually fix.

**Comment by iabdalkader** [comment]
Yeah I noticed this while testing `py_image_to`. It's very easy to reproduce if you convert the snapshot to anything, to forcing the lines to changes every frame. For example:

```Python
import sensor
import time
import image

sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QQVGA)

while True:
    sensor.snapshot().to_rainbow(color_palette=image.PALETTE_IRONBOW)
```

> When the number of frame buffers is set to 1 
> That said, unlike before, it's only one line near the top left of the frame. Not all over it.
> It doesn't seem to bother multiple buffer mode, which everyone uses. But, something to eventually fix.

That's not accurate. I see multiple lines get corrupted, almost every line randomly, there's no obvious pattern. Also, unless `image_to` switches to 1 buffer, this happens with multiple buffers too.
![1](https://github.com/openmv/openmv/assets/4498013/26c3d5ba-8102-48da-85b7-93fdf6e782c4) ![2](https://github.com/openmv/openmv/assets/4498013/3910c5fc-7d02-4dc2-b168-49049dc9e496)

**Comment by kwagyeman** [comment]
Okay, will spend time thinking more about this on Monday/Tuesday.
