### ISSUE TITLE
Enable sys.settrace in firmware.

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#2218]
With sys.settrace, we can use the single-step debugging function on the board.
This is very useful for debugging.

We just nee add `MICROPY_PY_SYS_SETTRACE` in MicroPython options.

**Comment by iabdalkader** [comment]
> We just nee add `MICROPY_PY_SYS_SETTRACE` in MicroPython options.

I've looked into this, and the docs says it impacts the performance, but more importantly it adds about 34 KBs to the firmware, so I'm not sure if we should enable it.

**Comment by kidswong999** [comment]
Because settrace requires additional performance and locals() cannot be implemented, we can turn it off and wait until micropython improves this feature in the future.
