### ISSUE TITLE
Can't build openmv for RaspberryPi  PICO Board

### ISSUE THREAD

**Issue by IotaHydrae** [openmv/openmv#2222]
**Describe the bug**

Can't build openmv for RaspberryPi  PICO Board

**To Reproduce**

I use

```
make -j$(nproc) TARGET=PICO -C src
```

and getting this

```
make: Entering directory '/home/developer/.sources/openmv/src'
make[1]: Entering directory '/home/developer/.sources/openmv/src/micropython/ports/rp2'
Makefile:18: The PICO* boards have been renamed to RPI_PICO*
Makefile:20: *** Invalid BOARD specified: boards/PICO.  Stop.
make[1]: Leaving directory '/home/developer/.sources/openmv/src/micropython/ports/rp2'
make: *** [/home/developer/.sources/openmv/src/omv/ports/rp2/omv_portconfig.mk:25: firmware] Error 2
make: Leaving directory '/home/developer/.sources/openmv/src'
```

**Expected behavior**

**Screenshots**

**Please complete the following information**
 - IDE version: [e.g. 2.6.8]
 - Firmware version: [e.g. 3.8.0]
 - Board: [e.g. OPENMV-H7+/Portenta]
 - OS: [e.g. Windows/Linux/iOs]

**Comment by kwagyeman** [comment]
That target is not maintained. The board name is: [ARDUINO_NANO_RP2040_CONNECT](https://github.com/openmv/openmv/tree/master/src/omv/boards/ARDUINO_NANO_RP2040_CONNECT)
