### ISSUE TITLE
HIMAX Sensors not working with Arduino Giga

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv#2226]
https://forums.openmv.io/t/failed-to-detect-hm0360-vga-monochrome-dvp-camera/9638/5

**Comment by iabdalkader** [comment]
This issue has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/failed-to-detect-hm0360-vga-monochrome-dvp-camera/9638/10

**Comment by kwagyeman** [comment]
Still waiting on Arduino to send the modules.
