### ISSUE TITLE
Build from source error for OPENMV4 target

### ISSUE THREAD

**Issue by Gnoth-404** [openmv/openmv#2246]
**Describe the bug**
I got a build error at bootloader step

**To Reproduce**
1. Follow build from source on Linux 
2. TARGET= OPENMV4

```
make[1]:` Leaving directory '/home/gnothha/openmv/src/bootloader'
/usr/local/arm-none-eabi/bin/../lib/gcc/arm-none-eabi/10.2.1/../../../../arm-none-eabi/bin/ld:/home/gnothha/openmv/src/build/stm32fxxx.lds:62: non constant or forward reference address expression for section .gc.blocks.table
collect2: error: ld returned 1 exit status
make: *** [/home/gnothha/openmv/src/omv/ports/stm32/omv_portconfig.mk:737: firmware] Error 1
```

**Please complete the following information**
 - IDE version: [e.g. 2.6.8]
 - Firmware version: [e.g. 3.8.0]
 - Board: OpenMVM4
 - OS: Linux Debian 12

**Comment by kwagyeman** [comment]
You need to use the version of GCC defined in the tools/ci.sh file.
