### ISSUE TITLE
RPC library not updated to use machine library in RT1062

### ISSUE THREAD

**Issue by TheSoupMasta** [openmv/openmv#2265]
**Describe the bug**
The RPC library is still using pyb dependency when it should be moved to machine dependency since the RT1062 no longer supports the stm32 pyb library.

**To Reproduce**
1. Open RPC example in the OpenMV IDE under examples.
2. Run the code.

**Expected behavior**
Example code runs and RPC can be used to remotely call functions without import errors.

**Please complete the following information**
 - IDE version: 4.1.5
 - Firmware version: 4.5.5
 - Board: OpenMV RT1062
 - OS: Windows 10

**Comment by kwagyeman** [comment]
@TheSoupMasta - Will get it done this week.
