### ISSUE TITLE
Light bleeding

### ISSUE THREAD

**Issue by Sejl** [openmv/openmv#227]
Light bleeds through via holes on the back of the image sensor.

**Comment by iabdalkader** [comment]
Hi,
The vias are all tented (painted over with the solder stop mask) which helps with the light bleeding but obviously doesn't completely stop it. I don't know of any other way to fix this (note cameras typically come in enclosures). If you have any **practical** suggestions (i.e. something we can do during manufacturing) please let me know and I'll forward to our factory.

**Comment by Sejl** [comment]
Hi,

Sorry, but other than standard tips ([for example here](https://www.pcbuniverse.com/pcbu-tech-tips.php?a=5)) I have no other suggestions for you. I have solved problem by painting over vias.

**Comment by scm6079** [comment]
This may be worth adding to the FAQ -- I was fighting terrible light bleed to the point vision tasks were impossible until simply adding a small piece of electrical tape over the back of the circuit board directly behind the image sensor area.

**Comment by kwagyeman** [comment]
We're going to add black stickers to the back of all OpenMV cameras for our next production run. For the current ones a piece of electrical tape will do.

**Comment by iabdalkader** [comment]
Hi, so we already use tented vias (one of the suggestions in the link above) and we're going to add the black stickers like @kwagyeman mentioned.

Additionally, we're in the process of designing a case. We were going to use transparent/clear plastic, but maybe now we should use an opaque color ?

**Comment by lorth** [comment]
Use plugged vias: https://www.pcbuniverse.com/pcbu-tech-tips.php?a=5

**Comment by kwagyeman** [comment]
Fixed with new black sticker on back.
