### ISSUE TITLE
openmv3  ADC function

### ISSUE THREAD

**Issue by 846354866** [openmv/openmv#229]
Hi, there is a problem that has been confusing for a long time, I want to achieve more than two ADC for data sampling, but I try to modify some of the source code, but still failed. Now I have no idea, I hope to get your help.

**Comment by iabdalkader** [comment]
You mean use two ADC channels ? Unfortunately there's only one channel broken out on the header.

**Comment by 846354866** [comment]
@iabdalkader 
Thank you very much for your answer! Yes, I would like to use two ADC channels, or I would like to use another channel (not just channel 5).

**Comment by iabdalkader** [comment]
There's only **1** channel broken out, sorry.

**Comment by 846354866** [comment]
Thank you! I have found other effective ways. There is an adc_init_all () function, I added some content, and now can achieve multiple channels data sampling.

**Comment by iabdalkader** [comment]
Okay glad you found a way to do what you want :) going to close this issue now, if there's something else please open another issue. If you have questions please use the forums.
