### ISSUE TITLE
face detector details

### ISSUE THREAD

**Issue by PVNathan** [openmv/openmv#230]
Hi,
I couldn't find the details regarding how the haar cascade is performed for the face detector. Can i know which file the actual math resides in? In face detection.py I see import image and then it says image.haarcascade but I couldn't ind where the image module is. I basically want to know how it detects the faces in detail. Appreciate your response. 
Thanks

**Comment by iabdalkader** [comment]
Here:
https://github.com/openmv/openmv/blob/master/src/omv/img/haar.c

**Comment by PVNathan** [comment]
Thanks. 
Also when I run the face_eye_detector.py it says no module named sensor. I am new to python and is there a readme where it says how to run the example py files?
Thanks

**Comment by iabdalkader** [comment]
Those modules are available on OpenMV only, the code will not work on your PC.

**Comment by PVNathan** [comment]
okay, thanks.
