### ISSUE TITLE
I cannot open openmv as a udisk while debuging in IDE is OK

### ISSUE THREAD

**Issue by jsbyysheng** [openmv/openmv#236]
### Steps to reproduce
1.Plug in openmv3 to a computer installed windows10 ver15063.

### Expected behaviour
1.See openmv3 as a udisk device and open it.
2.get "True" from function "usb_vcp.isconnected()" in my program.

### Actual behaviour
1.I cannot find udisk device unless I wait for more than 10 min.
2.always get "False" from function "usb_vcp.isconnected()" in my program.
3.Although 1 and 2 have happened, I can still use IDE to debug my program.
4.It seems that openmv3 will prevent new usb devices recognized by OS and cause unable to boot into the system.

### Describe your setup

**Operating system**:
windows10 build15063.332
**OpenMV IDE version:**
OpenMV IDE v1.5.2
**OpenMV firmware version:**
firmware2.4

**Comment by kwagyeman** [comment]
Yeah, I just encountered this same issue. I have no idea what's going on.

**Comment by iabdalkader** [comment]
Hi seems a recent update broke something, I'm looking into it.

Please open an new issue (or edit this one) and the follow the issue **template** (how to reproduce, expected vs. actual behavior, OS, FW, IDE version all that) so I can help you more.

**Comment by kwagyeman** [comment]
I also have a Ubuntu VM and it seems to work fine on that.

>> Finally, when I connect openmv3 to my computer, then plug in other usb devices, they have no response until I remove openmv3. Also, if I restart my computer with openmv3 plugged in, my computer will stop in startup state unless I remove openmv3.

Didn't notice this part, but, I bet I'm having the same issue.

We've cleared all other software issues for the next firmware release so I guess this will be our sole focus for the release. This issue kinda makes the system unusable.

**Comment by kwagyeman** [comment]
Yeah, I have the same 15063.296 OS build. I think windows changed some stuff on us in the driver level when they forced that system update a few days back. Me thinks all pyboards are broken too.

**Comment by jsbyysheng** [comment]
So sad to meet this problem. I'll edit this issue a little while. Thank u for paying attention to this issue.

**Comment by kwagyeman** [comment]
Seems to be the Windows 10 Creator update. Going to try playing around with driver files and see if this helps.

**Comment by jsbyysheng** [comment]
> Seems to be the Windows 10 Creator update. Going to try playing around with driver files and see if this helps.

playing around with driver files...I'm afraid it will result in disastrous consequence. 2333333

**Comment by kwagyeman** [comment]
Not Windows drivers. But, the ones we create for hardware. I.e. our INF files.

Sent from my Verizon Wireless 4G LTE Droid
On May 31, 2017 5:10 AM, jsbyysheng <notifications@github.com> wrote:

Seems to be the Windows 10 Creator update. Going to try playing around with driver files and see if this helps.

playing around with driver files...I'm afraid it will result in disastrous consequence. 2333333

**Comment by kwagyeman** [comment]
MP fixed this issue. We'll release a new firmware with a patch for this soon.
