### ISSUE TITLE
Revert size/bpp to 0.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv#2362]
Once the IDE uses w/h to check for valid frames, this can just be reverted: afcd12cb6aff0d5d2897a1f0d15a3e08fe10151c

Note that it will not be a breaking change because debug code always sent 0, 0, 0 for no frame.

**Comment by kwagyeman** [comment]
The IDE code already used w/h to check for valid frames. The issue was that the camera wouldn't send anything because if it saw size being 0 it would stop.

**Comment by iabdalkader** [comment]
> The issue was that the camera wouldn't send anything because if it saw size being 0 it would stop

The firmware always returns something. The old command would return 12 0-bytes. The new command, get_state, returns flags and 0s too.

**Comment by iabdalkader** [comment]
Reverted.
