### ISSUE TITLE
Wrong alpha passed to draw_image or from draw_image to gpu.

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv#2438]
In so many places, alpha is passed as 256, when it should be 0...255:
```C
imlib/draw.c:            imlib_draw_image(&t_src_img, src_img, 0, 0, x_scale, y_scale, roi,
imlib/draw.c-                             -1, 256, NULL, NULL,
imlib/draw.c-                             hint & (IMAGE_HINT_AREA | IMAGE_HINT_BILINEAR | IMAGE_HINT_BICUBIC),
imlib/draw.c-                             NULL, NULL, NULL);
```

**Comment by kwagyeman** [comment]
@iabdalkader - This is correct. The -1 is the RGB channel extraction. If it were 0 then that would cause red channel extraction.

**Comment by iabdalkader** [comment]
> @iabdalkader - This is correct. The -1 is the RGB channel extraction. If it were 0 then that would cause red channel extraction.

`-1, 256,` 256 should be 255... Alpha is an int from 0-> 255 0%->100%

**Comment by kwagyeman** [comment]
Yes, we should fix this to make it industry standard.

**Comment by kwagyeman** [comment]
https://github.com/openmv/openmv/pull/2486
