### ISSUE TITLE
OV5640 Exposure Calculation

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv#2457]
Needs to be improved: https://forums.openmv.io/t/ov5640-exposure-time-not-making-sense-with-fps/10105/2

**Comment by iabdalkader** [comment]
This issue has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/ov5640-exposure-time-not-making-sense-with-fps/10105/3

**Comment by iabdalkader** [comment]
Fixed
