### ISSUE TITLE
tf_image_classification.py Example results in ValueError: Failed to allocate tensors

### ISSUE THREAD

**Issue by yochem** [openmv/openmv#2462]
**Describe the bug**

On my OpenMV H7 when trying to run the Example TF image classification file (with no modifications what so ever) I get a `ValueError: Failed to allocate tensors`. I added the tflite file and labels file to the board.

**To Reproduce**
Steps to reproduce the behavior (MacOS):
1. Connect board
2. File > Examples > Machine Learning > Tensorflow > tf_image_classification.py
3. Tools > Machine Vision > CNN Network Library > mobilenet > mobilenet_v1_0.5_128_quant.tflite to /Volumes/NO NAME
4. Tools > Machine Vision > CNN Network Library > mobilenet > mobilenet_labels.txt to /Volumes/NO NAME
5. Start (run script)

**Expected behavior**
No errors, board is able to perform image classification

**Screenshots**

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/9b666933-0dbd-48f9-95d2-8ad80b0aaaf3">

**Please complete the following information**
 - IDE version: 4.2.4
 - Firmware version: 4.5.9
 - Board: OPENMV-H7+ R3 12/13/2019
 - OS: MacOS v15.0 (24A335)

**Comment by yochem** [comment]
Same thing on the Arduino Portenta STM32H747.

**Comment by kwagyeman** [comment]
Hi, I will remove the script. Support was removed from TensorFlow run mobilenet. We left the script in to show off how the ImageClassification task works. But, those models are no longer runnable. We should delete them.

Please use Edge Impulse to generate an Image Classification network: https://edgeimpulse.com/

**Comment by kwagyeman** [comment]
Please leave this open. I'll need to send a PR to delete this old stuff.
