### ISSUE TITLE
Servo(3) does not exist on OpenMV3 M7

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#256]
Hello,
IDE version: 1.6.0
firmware version: 1.4.1

I found the bug:

```
>>> s3 = Servo(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Servo 3 does not exist
```

**Comment by kwagyeman** [comment]
Ibrahim, did you test the 3rd servo channel when you added it?

**Comment by iabdalkader** [comment]
No it's not enabled.

**Comment by iabdalkader** [comment]
@kidswong999 can you test and confirm it works ? Thanks.
