### ISSUE TITLE
Problem saving VGA JPGs

### ISSUE THREAD

**Issue by Yo-Po** [openmv/openmv#260]
### Steps to reproduce
```
import os, pyb, sensor, image, time, sys

sensor.reset()                               # Reset and initialize the sensor.
sensor.set_pixformat(sensor.RGB565)          # Set pixel format to RGB565 (or GRAYSCALE)
sensor.set_framesize(sensor.VGA)             # Set frame size to QVGA (320x240)
sensor.skip_frames( time = 2000 )            # Wait for settings take effect.
if 1:
    folder = "temp"
    if not folder in os.listdir():
        os.mkdir(folder) # Make a directory
    else:
        print("ERROR - reusing the same folder")
        pyb.LED(3).off
        pyb.LED(1).on()
        time.sleep(10000)
        sys.exit(0)
    for i in range(10):
        file_path = "%s/image_%d.jpg" % (folder, i)
        pyb.LED(2).on()
        img = sensor.snapshot()
        pyb.LED(2).off()
        img.save( file_path, quality=100)
        time.sleep(500)
```
### Expected behaviour
Jpegs should appear at the desired folder

### Actual behaviour
The jpegs are corrupted. 
This Does not happen for QVGA, or when using windowing to reduce the frame size, which implies a memory issue.
![image_6](https://user-images.githubusercontent.com/31315197/29671148-6dd7985a-88f1-11e7-8566-87807689c7fc.jpg)

### Describe your setup

**Operating system**:

**OpenMV IDE version:**

**OpenMV firmware version:**
2.5.0

**Comment by iabdalkader** [comment]
Fixed in https://github.com/openmv/openmv/commit/9f71b89187a3d2eb2c2fda7fd038010a75ca26fe more fixes to image format issues will follow.
