### ISSUE TITLE
Need Explanation!

### ISSUE THREAD

**Issue by MaurinElectroTextile** [openmv/openmv#264]
Can you just explain me the difference between *pixels & *data
Why are you using this union?

https://github.com/openmv/openmv/blob/6f30fb6ce7d894df3ff44798f81ee1464004173d/src/omv/img/imlib.h#L338-L346

**Comment by kwagyeman** [comment]
They are the same. There's just legacy code that requires one name over the other. Please look at recent code commits to see which one is the favored one I've been changing stuff to use.
