### ISSUE TITLE
UART init problem in Pre-V2.6.0

### ISSUE THREAD

**Issue by jackeychuang** [openmv/openmv#269]
### Steps to reproduce
1. call:  uart = UART(3, 115200)
2.
3.

### Expected behaviour
It is okay in V2.5.0

### Actual behaviour
IDE shows: UART(3) is not exist

### Describe your setup

**Operating system**:

**OpenMV IDE version:** V1.7.1

**OpenMV firmware version:** Pre-V2.6.0

**Comment by iabdalkader** [comment]
Hi, this bug was fixed *after* updating the firmware images. If you rebuild the images UART(3) will work.
