### ISSUE TITLE
The sensor.set_image_filter command is not working

### ISSUE THREAD

**Issue by AlexisTM** [openmv/openmv#270]
The example crashes: https://github.com/openmv/openmv/edit/master/usr/examples/04-Image-Filters/grayscale_filter.py

### Steps to reproduce
1. Use : sensor.set_image_filter(sensor.FILTER_BW, lower=128, upper=255)

### Expected behaviour
Compiles

### Actual behaviour
Crashes

### Describe your setup
* OpenMV 7

**OpenMV IDE version:**
* Downloaded today

**OpenMV firmware version:**
* Downloaded today (2.5.0)

**Comment by iabdalkader** [comment]
Hi,
This feature was removed, it's not very useful. Will remove the example. Thanks.
