### ISSUE TITLE
sensor.snapshot(line_filter=some_filter) crashes

### ISSUE THREAD

**Issue by AlexisTM** [openmv/openmv#271]
The line buffer is not working properly.

### Steps to reproduce
Use the following

```python
def bwfilter(src, dst):
  print("Lenghts : %i, %i" % (len(src), len(dst) ))

while(True):
    img = sensor.snapshot(line_filter=bwfilter)
```

### Expected behaviour
It should print:

>   Lenghts : 640, 640

### Actual behaviour
It prints:

> Lenghts : 1280, 640

### Describe your setup

**Operating system**:
* Linux ubuntu 16.04 x64

**OpenMV IDE version:**
* last: 1.7.1

**OpenMV firmware version:**
* last: 2.5.0

**Comment by iabdalkader** [comment]
The sensor is set to output 2 bytes per pixel (YUYV) for the GRAYSCALE format and the destination buffer is 1 byte per pixel. So for VGA, the buffer sizes should be 640*2 and 640 for src and dst respectively.
