### ISSUE TITLE
Save object feature failed

### ISSUE THREAD

**Issue by zz2633105** [openmv/openmv#279]
kpts1 = img.find_keypoints(max_keypoints=150, threshold=10, scale_factor=1.2)
 image.save_descriptor("/desc.orb",kpts1)

Save object feature failed???

**IDE version:1.7.1

**Firmware version:2.5.0

**Operating system:win10

**Comment by zz2633105** [comment]
I want to use save_descriptor function to preserve the feature points of the object, but it is wrong. The error message is "can not convert 'kp_desc' object to str implicitly"

**Comment by iabdalkader** [comment]
Hi, you should switch the args `image.save_descriptor(kpts, path)` The docs for this function is outdated @kwagyeman.

**Comment by zz2633105** [comment]
@iabdalkader Thank you
