### ISSUE TITLE
how to make firmware of openmv2 for stm32f407?

### ISSUE THREAD

**Issue by lw944936908** [openmv/openmv#281]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Describe your setup

**IDE version:**

**Firmware version:**

**Operating system:**

### For developers

**GCC version:**

**Build target:**

**Comment by iabdalkader** [comment]
407 is no longer supported.
