### ISSUE TITLE
how use it landing UAV(px4 or apm)

### ISSUE THREAD

**Issue by moonsummer** [openmv/openmv#302]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Describe your setup

**IDE version:**

**Firmware version:**

**Operating system:**

### For developers

**GCC version:**

**Build target:**

**Comment by kwagyeman** [comment]
Please post on the forum.

**Comment by moonsummer** [comment]
ok.I detail  description this project matter on the forum. thanks.
