### ISSUE TITLE
How to get raw data in ROS?

### ISSUE THREAD

**Issue by stevechan1993** [openmv/openmv#315]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Describe your setup

**IDE version:**

**Firmware version:**

**Operating system:**

### For developers

**GCC version:**

**Build target:**

**Comment by iabdalkader** [comment]
Hi, please post questions to the forums http://forums.openmv.io I don't have experience with ROS, other people may help.
