### ISSUE TITLE
Fix saving of files

### ISSUE THREAD

**Issue by aakoch** [openmv/openmv#341]
As discussed here: http://forums.openmv.io/viewtopic.php?p=4397#p4397

### Steps to reproduce
1. sensor.snapshot().save("image.jpg")

### Expected behaviour
New file named "image.jpg" in the correct format. 

### Actual behaviour
File with extra extension: "image.jpg.jpg"
File isn't recognized by the OS as an image

### Describe your setup
IDE version:
1.8.2

Firmware version:
2.7.0

Operating system:
macOS High Sierra

**Comment by iabdalkader** [comment]
Fixed, thanks for reporting bugs.
