### ISSUE TITLE
flush files when saving script to cam

### ISSUE THREAD

**Issue by aakoch** [openmv/openmv#342]
As discussed here: http://forums.openmv.io/viewtopic.php?p=4397#p4397

When the "Save script to OpenMV Cam" button is clicked, flush file contents.

IDE version: 1.8.2
Firmware version: 2.7.0
Operating system: macOS High Sierra

**Comment by kwagyeman** [comment]
Hi, the flushing was a known error in the IDE I introduced trying to fix another problem and has been fixed for the next release.
