### ISSUE TITLE
optical_flow.py example script doesn't work

### ISSUE THREAD

**Issue by aakoch** [openmv/openmv#344]
### Steps to reproduce
1. Select File -> Examples -> Feature-Detection -> optical_flow.py
2. Run

### Expected behaviour
No errors

### Actual behaviour
AttributeError: 'module' object has no attribute 'B64x32'

If I change it to B64X64 and re-run, I get this error:
TypeError: 'displacement' object is not iterable

### Describe your setup

**IDE version:**
1.8.2

**Firmware version:**
2.7.0

**Operating system:**
macOS High Sierra

Also, there is a comment "# or B40x30 or B64x64" but there is no "B40X30" constant

**Comment by kwagyeman** [comment]
That's an old script that should have been deleted. Please see the optical flow examples under 22 optical flow.
