### ISSUE TITLE
line_filter.py example doesn't work

### ISSUE THREAD

**Issue by aakoch** [openmv/openmv#345]
### Steps to reproduce
1. Select File -> Examples -> 04-Image-Filters -> line_filter.py
2. Run

### Expected behaviour
Discernible image

### Actual behaviour
Strange images and memory errors
![line_filter1](https://user-images.githubusercontent.com/137713/39102363-c81b4be2-4668-11e8-980e-d5198606bc20.jpg)
![line_filter3](https://user-images.githubusercontent.com/137713/39102364-ca8d9e5c-4668-11e8-919c-7ab815112011.jpg)

Every few seconds, this appears in the terminal:
MemoryError: 

### Describe your setup

**IDE version:**
1.8.2

**Firmware version:**
2.7.0

**Operating system:**
macOS High Sierra

**Comment by kwagyeman** [comment]
That script needs to be deleted. Sorry about this junk being in there. It's been removed for the latest release.
