### ISSUE TITLE
No module named 'ussl'

### ISSUE THREAD

**Issue by martindr** [openmv/openmv#348]
### Steps to reproduce
1. In the OpenMV IDE start a new file.
2. import ussl 
3. Connect to OpenMV 7 and run the program

### Expected behaviour
Program should compile and run

### Actual behaviour
Error: no module named 'ussl'

### Describe your setup
**IDE Version** 
1.9.0

**Firmware version:**
2.9.0

**Operating system:**
Windows 10

**Comment by iabdalkader** [comment]
This module is not implemented for Micropython stm32 port.

**Comment by Ascarron** [comment]
Sorry for re-opening this issue. The module was recently updated and opened for stm32 port. Could you please include it in the next firmware build?

**Comment by kwagyeman** [comment]
Yes, will do.

**Comment by dipeshwor** [comment]
Hi, I am getting a '301 permanently moved' error when accessing any https link. The usocket in OpenMV works for http links like the open weather data API but gives the 301 error for https links like Canvas API. I came across this issue in the forum and think it's related to what I am trying to do. I probably need the ussl module for the usocket to work properly. Please let me know if there are any updates on the issue. Thanks.

**Comment by iabdalkader** [comment]
It's on my TODO list for WINC, I'll also update the module firmware and driver.

**Comment by iabdalkader** [comment]
Hi, the ussl module is now available in the [latest beta release](https://github.com/openmv/openmv/releases/tag/v3.5.0.beta.3) (with mbedtls), additionally the WINC1500 host driver and firmware have been updated to the latest (v19.3.0/v19.6.1). Note the new release requires a WINC1500 firmware update (included with the release).
