### ISSUE TITLE
no module named 'uctypes'

### ISSUE THREAD

**Issue by DeqingSun** [openmv/openmv#360]
### Steps to reproduce
1. Try to write my own driver of Neopixel with inline assembler
2. Can not pass in an array
3.

### Expected behaviour
Tell us what should happen
http://docs.openmv.io/reference/asm_thumb2_hints_tips.html#multiple-arguments 
This feature should work

### Actual behaviour
Tell us what happens instead

### Describe your setup

**IDE version:**

**Firmware version:**

**Operating system:**

### For developers

**GCC version:**

**Build target:**

**Comment by iabdalkader** [comment]
Enabled.
