### ISSUE TITLE
Saving ".raw" images is not working.

### ISSUE THREAD

**Issue by oelalfey2010** [openmv/openmv#365]
### Steps to reproduce
1.save image as raw
2.reset camera
3.check memory card files 
4.saved file is 0 KBs.

### Expected behaviour
i am trying to save image.raw using function
sensor.snapshot().save("bayer.raw")

### Actual behaviour
what happens which i check file inside memory it becomes 0 bytes

### Describe your setup

IDE version:
OpenMV IDE 2.0.0

Firmware version:
3.0.0

Operating system:
windows 7 64 bit

### For developers

GCC version:

Build target:

**Comment by kwagyeman** [comment]
This is unrelated to the IDE but is a firmware issue. It will get fixed.

**Comment by iabdalkader** [comment]
@kwagyeman Seems .raw might not be working (waiting for Omar to confirm). Could it be related to the IDE not ejecting the FS anymore ?
