### ISSUE TITLE
importError: cannot import name CAN

### ISSUE THREAD

**Issue by gdramos** [openmv/openmv#370]
Unable to import CAN module on OpenMV Cam M7

**IDE version:**
2.0.0
**Firmware version:**
3.0.0
**Operating system:**
Windows 10

**Comment by iabdalkader** [comment]
from pyb import  CAN

**Comment by bauer-san** [comment]
I have the same error with the same system configuration with the import stated by @iabdalkader 
Why is it closed?

**Comment by iabdalkader** [comment]
@bauer-san @gdramos CAN was disabled by the last MP update and I re-enabled it in bdacce048dc4fbf3d8afae9b146cd87ffc87b24d

It will be re-enabled in the next release.

>> Why is it closed?

Because it's fixed, I should've mentioned that :) re-opened it if you would like to add something.

**Comment by gdramos** [comment]
Oh ok. Cool. I figured it was something like that.
Thanks, @iabdalkader!

**Comment by bauer-san** [comment]
Thank you for the info.
Is the next release already planned?  What is your typical release cadence?

**Comment by iabdalkader** [comment]
>> Is the next release already planned? What is your typical release cadence?

Yes very soon, typically 1-3 months

**Comment by iabdalkader** [comment]
Hi, the new FW is finally out:

https://github.com/openmv/openmv/releases/tag/3.1

**Comment by x79133000** [comment]
FW ver. 4.3.1
IDE ver. 2.2.0
Unable to import CAN module on OpenMV Cam H7. Is it disabled again?

**Comment by iabdalkader** [comment]
@x79133000 No it's still not supported on the H7 yet, it will be supported in the next release.

**Comment by x79133000** [comment]
Thank you for the update.
