### ISSUE TITLE
Hello, I designed a new board based on Openmv2 schematic with STM32F427VIT6

### ISSUE THREAD

**Issue by UBTEDU** [openmv/openmv#372]
Hello, I designed a new board based on Openmv2 schematic with STM32F427VIT6
Flash changed from 1M to 2M.
How to allocate flash?
https://github.com/openmv/openmv/blob/m ... rdconfig.h

**Comment by iabdalkader** [comment]
Hi, please use the forums to ask questions, this is for developers and to report issues with the firmware.
