### ISSUE TITLE
Failed to build openmv from source...

### ISSUE THREAD

**Issue by jiapei100** [openmv/openmv#373]
Hi, all:

My working environment:
**Ubuntu**: 18.04.1
**GCC**: gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
**arm-none-eabi-gcc**: arm-none-eabi-gcc (GNU MCU Eclipse ARM Embedded GCC, 64-bit) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
**openmv**: (git of September 11, 2018)
**micropython**: (git of September 11, 2018)

1. I can successfully build **micropython/ports/unix** and have it run on my laptop. However, I don't have some of the packages from [http://docs.openmv.io/library/index.html](http://docs.openmv.io/library/index.html) , including:

1) MicroPython-specific libraries:
- machine
- network

2) Libraries specific to the OpenMV Cam
- pyb
- time
- sensor
- image
- nn
- gif
- mjpeg
- lcd
- fir
-omv

2. I realize I need to build **openmv** from source, together with **micropython**. I strictly follow 
**Linux Installation** at [https://github.com/openmv/openmv/wiki](https://github.com/openmv/openmv/wiki)

It seems **Makefile**s for building **openmv** are all for **ports/stm32**. Therefore, I met the following **ERROR** messages (even if with **arm-none-eabi-gcc** installed):

> make[1]: Entering directory '....../openmv/src/micropython/ports/stm32'
> Makefile:11: *** Invalid BOARD specified: boards/OPENMV3.  Stop.
> make[1]: Leaving directory '....../openmv/src/micropython/ports/stm32'
> Makefile:428: recipe for target 'FIRMWARE_OBJS' failed
> make: *** [FIRMWARE_OBJS] Error 2

Just wonder how to build **openmv** together with **micropython** from source? In other words, how to build **micropython** with the supported board **openmv**? 

It looks like it's just a directory problem?

```
git checkout openmv
```
There is **NO** openmv branch at all under **micropython** ....

Can you please help?

Cheers
Pei

**Comment by kwagyeman** [comment]
You have to recursively pull the GitHub repo. Please Google git recursive pull
