### ISSUE TITLE
A question about the use of  "lbp_weights"  in function "imlib_lbp_desc_distance" in src/omv/img/lbp.c

### ISSUE THREAD

**Issue by bj-wanghz** [openmv/openmv#394]
Hi, 
    In src/omv/img/lbp.c, lbp_weights[] is used to calculate the sum of the weighted distance. And I think that the index `i%LBP_HIST_SIZE` means which one of the 7*7 regions `d0[i]` and `d1[i]` belong to , am I right? If so, I guess `i / LBP_HIST_SIZE` shall be used instead of `i%LBP_HIST_SIZE`. Also if `i%LBP_HIST_SIZE` is used, the index value may be invalid, as the size of lbp_weights is 49, but LBP_HIST_SIZE is 59.

**Comment by iabdalkader** [comment]
@bj-wanghz You're right it's a bug, it should be `/` not `%`. Thanks for finding it. Would you like to send a PR to fix it ?
