### ISSUE TITLE
Find within rectangle

### ISSUE THREAD

**Issue by shimniok** [openmv/openmv#40]
If we don't have it yet (I didn't see anything exactly like it in source) it'd be really handy to be able to constrain blob detection (or anything, really) to a bounding rectangle. E.g., pips on a die or finding color "markers" red square in blue square, pink square next to green square, etc.

**Comment by iabdalkader** [comment]
It exists for some algorithms, where it seemed more useful, say when you want face keypoints, I guess it could be added to blobs too

**Comment by kwagyeman** [comment]
Done.
