### ISSUE TITLE
Appeding data to .txt

### ISSUE THREAD

**Issue by Franzisdrak** [openmv/openmv#413]
Hi there,

i am trying to open a .txt-file and append each time there is new data. Sadly when executing my file is not opened.
I also tried with the write option "w", which works, but i need to append the data.

```
  result_string = "Test"
  with open("results.txt", "a") as myfile:
            myfile.write(result_string)
```

Edit: After checking again, it looks like the data is actually written to my attached SD card, though it doesn't start newlines, and the changes become visible only after i disconnect/connect the camera again.

**Comment by kwagyeman** [comment]
Hi, this is due to how OSes cache the file system. We can't fix this as it's the OS that doesn't bother re-reading the drive. All modern OSs assume drives can't modify the file system themselves.
