### ISSUE TITLE
No support for loading jpg object into RAM

### ISSUE THREAD

**Issue by raryanpur** [openmv/openmv#414]
### Steps to reproduce

Try to load a jpg image with the `image.Image` constructor, as in

```
img = image.Image("/image.jpg", copy_to_fb=True)
```

### Expected behaviour

Loading a jpg into RAM using the `Image` class constructor shouldn't throw an error. Per the documentation for `class image.Image`, the `image.Image(path[, copy_to_fb=False])` constructor supports both `jpg` and `jpeg` image files. At the least, there should be support to load a `jpg` object into RAM.

### Actual behaviour
Loading a `jpg` image into RAM using the `Image` class constructor throws an error `OSError: Unsupported format!`

**Comment by iabdalkader** [comment]
Actually the library doesn't support loading JPEG image. This needs to be fixed in the docs @kwagyeman.

**Comment by kwagyeman** [comment]
Can you add this feature @ibrahim.

**Comment by kwagyeman** [comment]
@iabdalkader

**Comment by raryanpur** [comment]
Thanks guys!

**Comment by iabdalkader** [comment]
Fixed, many years ago :sweat_smile:
