### ISSUE TITLE
memory corruption with jpeg.c by using compress()

### ISSUE THREAD

**Issue by pyresChris66** [openmv/openmv#417]
hello, 

### Version
Openmv IDE version: 2.0.0
Firmware version: 3.0.0
Operating system: Windows 10

### Actual behaviour
I have some memory corruptions with jpeg.c by using compress().

###  Test code :
```
import sensor, image, pyb

red_led=pyb.LED(1)
blue_led=pyb.LED(3)
red_led.off()
blue_led.off()

sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.VGA)
sensor.skip_frames(time=500)

quality = 94

while(True):
   img=sensor.snapshot()
   try:
      img.compress(quality)
      blue_led.off()
      red_led.toggle()
   except:
      red_led.off()
      blue_led.toggle()
```

### Steps to reproduce
1. At start the compression works on static subject (ceiling): the red led is flashing.
2. If i put my hand in front of the camera, the compression dont works : the blue led is flashing.
3. But if i take off my hand, the compression still doesnt work.... : blue led is still flashing

### Expected behaviour
The compression should work with any value between 0 and 100 (or this value should be limited ?).
If it doesnt, the compression should free the memory or dont memory leak.

Thanks,

**Comment by iabdalkader** [comment]
Thanks for reporting this bug, it's fixed now.

**Comment by kwagyeman** [comment]
Can you rebuild the firmware and post the fixed on on the forum issue? http://forums.openmv.io/viewtopic.php?f=6&t=1082

**Comment by iabdalkader** [comment]
@kwagyeman I think @pyresChris66 can build the firmware.
