### ISSUE TITLE
Connecting to WiFi board

### ISSUE THREAD

**Issue by chrisbuerginrogers** [openmv/openmv#419]
### Steps to reproduce
1. Connect board
2. Connect OpenMV to REPL
3. type 
>>> import network
>>> 
>>> wlan = network.WINC()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: failed to init WINC1500 module

### Expected behaviour
it should connect

### Actual behaviour
got an error

### Describe your setup

**IDE version:**
2.0.0

**Firmware version:**
3.0.0

**Operating system:**
MAC

### For developers

**GCC version:**

**Build target:**

**Comment by iabdalkader** [comment]
I think this issue was resolved.
