### ISSUE TITLE
Add support for protobuf 

### ISSUE THREAD

**Issue by UBTEDU** [openmv/openmv#420]
Add support for protobuf ?

**Comment by kwagyeman** [comment]
?

**Comment by UBTEDU** [comment]
Google Protocol Buffers

**Comment by UBTEDU** [comment]
> ?

Google Protocol Buffers

**Comment by kwagyeman** [comment]
Yeah, I got that. But, you didn't define what it's for, how it's to be used, etc.

**Comment by UBTEDU** [comment]
> Yeah, I got that. But, you didn't define what it's for, how it's to be used, etc.

Can the openmv support protobuf? like nanopb can support arduino and stm32
https://github.com/nanopb/nanopb

**Comment by kwagyeman** [comment]
You aren't describing what this is for.

**Comment by iabdalkader** [comment]
I see you already have opened the same issue at micropython https://github.com/micropython/micropython/issues/4200 When it gets supported by MicroPython we'll enable it.
