### ISSUE TITLE
AMG8833 FIR needs 90 degree rotation

### ISSUE THREAD

**Issue by kobaan** [openmv/openmv#421]
Probably the sensor matrix is read incorrectly here:
https://github.com/openmv/openmv/blob/master/src/omv/py/py_fir.c#L563
https://github.com/openmv/openmv/blob/master/src/omv/py/py_fir.c#L549

### Steps to reproduce
1. Connect AMG8833 sensor, and orient it so that the metal casing is on the left (silkscreen is readable)
2. Run examples for thermopile AMG8833_overlay
3. realize that the thermal image needs to be rotated by 90 degrees clockwise

### Expected behaviour
thermal image should overlay with video image

### Actual behaviour
thermal image is rotate 90 degrees counter clockwise

### Describe your setup
Adafruit AMG8833 breakout board connected to OpenMV M7

When I rotate the image90 degrees clockwise  in software everything is correct.

**IDE version:**
2.1.0
**Firmware version:**
3.2.0
**Operating system:**
OSX

**Comment by kwagyeman** [comment]
I fixed the AMG rotation and MLX90640 horizontal mirror. I will be adding bicubic upscaling too in another OR.
