### ISSUE TITLE
JPEG encoding for resolutions of non-multiple of 8

### ISSUE THREAD

**Issue by want2bfree** [openmv/openmv#423]
### Steps to reproduce
1. Set the image resolution as non-multiple of 8, for example, QQQVGA (80x60).
2. 
3.

### Expected behaviour
Images should be displayed correctly even for resolutions of non-multiple of 8.

### Actual behaviour
There appear some noisy lines at the edges of images.

### Describe your setup

**IDE version: 2.0.0

**Firmware version: 3.0.0

**Operating system: Windows 7

### For developers

**GCC version:**

**Build target:**

**Comment by kwagyeman** [comment]
Ibrahim is fixing this as we speak.

**Comment by iabdalkader** [comment]
Fixed in #425
