### ISSUE TITLE
btree module are not available in OpenMV firmware

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#427]
**OpenMV version:** OpenMV3
**Firmware version:** 3.2.0

`btree` module are not available in OpenMV firmware. 
Maybe the code didn't activate this feature.

### Code
```
import btree
```

### Actual behaviour
ImportError: no module named 'btree'

http://docs.openmv.io/library/btree.html

**Comment by kwagyeman** [comment]
Ibrahim, can you fix this

**Comment by iabdalkader** [comment]
I don't think this module is supported by the stm32 port.

**Comment by iabdalkader** [comment]
Fixed in #533
