### ISSUE TITLE
ADC P6 not work on OpenMV4 H7

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#453]
```python
from pyb import ADC
adc = ADC("P6")
print(adc.read() * 3.3 / 4095)
```
output
```
using channel 19
1.21685
```
But the 1.21685 value is wrong.
OpenMV3 M7 is correct.

firmware: 3.2.0
OpenMV4 H7

**Comment by kwagyeman** [comment]
Thanks KS for finding this. Likely an issue with the HAL. Ibrahim can fix.

**Comment by iabdalkader** [comment]
fixed
