### ISSUE TITLE
undefined reference to `fb_alloc_free_till_mark'

### ISSUE THREAD

**Issue by HarryZeng** [openmv/openmv#455]
### Steps to reproduce
1.make -C mpy-cross
2.display "undefined reference to `fb_alloc_free_till_mark'" at objstr.o: In function `bad_implicit_conversion':

why

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Describe your setup

**IDE version:**

**Firmware version:**

**Operating system:**

### For developers

**GCC version:**

**Build target:**

**Comment by kwagyeman** [comment]
It's in nlr.h. Comment it out for a cross build.

**Comment by HarryZeng** [comment]
Thank you,Comment it out in nlr.h is ok.
