### ISSUE TITLE
IDE 1.1 will not run in windows 10

### ISSUE THREAD

**Issue by rkertesz** [openmv/openmv#49]
Runs on windows 7 but not on win 10. 
Double clicking it doesn't pop up a single message box or anything but a spinning circle for 3 seconds. Nothing shows up in task manager.

**Comment by iabdalkader** [comment]
Will test on Windows 10, in the meantime, could you try to run it from CMD ? see if it prints any messages.
Thanks!

**Comment by rkertesz** [comment]
I tried running from command line. I simply executed the executable and it when to the next command prompt after thinking that it started the program. No error message.

**Comment by iabdalkader** [comment]
Okay, will test it on Windows 10 and get back to you.

**Comment by iabdalkader** [comment]
Tested on Windows 8 64-bit and Windows 10 64-bit:
![screenshot-windows8 running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/4498013/9558015/1a76df6a-4de1-11e5-8c54-333b91b038d9.png)

![screenshot-windows-10 running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/4498013/9558753/b39c1946-4de9-11e5-957f-23d2b9d07290.png)

**Comment by rkertesz** [comment]
Hm. That is interesting.
Is there a prerequisite that needs to be installed? Maybe my computer (microsoft surface pro 3) was docked (I don’t recall)? That could have caused a video driver type issue?
I didn’t see it in the task tray either though. 
Are there any steps that i should follow other than double clicking the executable? Do i need to plug in the OpenMV beforehand?
I tried all sorts of different modes.
I have lots of services running too. Maybe my antivirus, maybe conflict with my installed python or other service?

**Comment by iabdalkader** [comment]
No it just worked out of the box, it could be an antivirus.

**Comment by kwagyeman** [comment]
Old.
