### ISSUE TITLE
MavLink integration ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [openmv/openmv#501]
Have someone considered integrating [PyMavLink](https://github.com/ArduPilot/pymavlink) to openMV ?

Or thought about away to import [DroneKit](http://dronekit.io/) into openMV for MavLink Communication ?

I have seen the MavLink examples in the codebase and i was wondering if **PyMavLink** would be a better way than using ```struct``` ?

**Comment by kwagyeman** [comment]
Hi, theres like an active thread on the forum about this: https://forums.openmv.io/viewtopic.php?f=6&t=241
