### ISSUE TITLE
Hi there.  What would it take to port some of this code over to an ESP32?

### ISSUE THREAD

**Issue by Tylersuard** [openmv/openmv#504]
I'm planning to get an OpenMV cam as well, but I was wondering if there's a way to port some of this code to the ESP32.  The ESP-EYE has 32mb of flash memory, and it has some AI code repos, but they are written in C and not in Python.  Because the ESP32 can also be flashed with Micropython, I was hoping to get some computer vision programs onto the ESP32.  Is that possible?  Thanks!

**Comment by kwagyeman** [comment]
Yeah, you can easily just grab the C code and keep grabbing parts until you fix all compile errors. That said don't expect performance from the ESP32. QSPI flash and ram aren't good for vision algorithms where you need a really high memory bandwidth.
