### ISSUE TITLE
Files for lenet ml

### ISSUE THREAD

**Issue by bryansosa** [openmv/openmv#507]
Hi there,

I was wondering if you can provide the files:

caffe/examples/mnist/mean.binaryproto
models/lenet/lenet_iter_10000.caffemodel

I am running an experiment on a m3 processor but I am having a hard time to generate those files.

If not possible to upload to github, can you send them to me personally? I would appreciate that!

Thank you very much beforehand.

**Comment by kwagyeman** [comment]
Hi, we provide the converted model output. What's the need of the iter model?

**Comment by bryansosa** [comment]
I want to generate the c code as in https://github.com/ARM-software/ML-examples/tree/master/cmsisnn-cifar10

**Comment by kwagyeman** [comment]
I see. Um, I have the left over files on my deep learning desktop. I can get them to you later.

**Comment by bryansosa** [comment]
I would really appreciate this! Thanks a lot :) ... Will you upload them to the repository or send them to me personally?

**Comment by kwagyeman** [comment]
Um, well, I could send you the files in a zip. I think you need more than just the itermodel.

**Comment by bryansosa** [comment]
Ok you can send them to bsosabar@uccs.edu 

Thanks!
Bryan.

**Comment by bryansosa** [comment]
Hi @kwagyeman ,

I wonder if you were able to get a hold on the ML file?

Thank you very much.

**Comment by kwagyeman** [comment]
Sent.
