### ISSUE TITLE
binary function wrong in RGB565

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#513]
example code:
https://github.com/openmv/openmv/blob/master/scripts/examples/04-Image-Filters/erode_and_dilate.py

when Grayscale, it works great.
![image](https://user-images.githubusercontent.com/9582040/56742252-f2f6bf80-67a6-11e9-97e2-f79f18e14ee1.png)

when RGB565, the white turned gray.
![image](https://user-images.githubusercontent.com/9582040/56742221-e07c8600-67a6-11e9-8e2f-5c7e210536d5.png)

Maybe there are bugs in binary function.https://github.com/openmv/openmv/blob/1412a2d23410436091be84ff3fc6b5b520cf8061/src/omv/img/binary.c

**IDE version:** 2.2.0
**Firmware version:** 3.3.1

**Comment by ychxing** [comment]
Function binary() doesn't work correctly on my OpenMV3 board after updated firmware version to 3.3.1

**Comment by kwagyeman** [comment]
Will fix.

**Comment by kwagyeman** [comment]
Fixed, was due to some missing parens on a define.

**Comment by ychxing** [comment]
when will upgrade a new fixed firmware?
