### ISSUE TITLE
missing break statement in switch-case in py_net_search function.

### ISSUE THREAD

**Issue by ddech** [openmv/openmv#516]
Hi,

function "py_net_search" in file "openmv/src/omv/py/py_nn.c".
I found that switch-case at line 204 to 220 is missing break statement in each case.
this will lead to hardfault because of index overflow.

IDE version: 2.2.0
Firmware version: 3.31
Operating system: Windows 10
GCC version: 7.3.1 20180622

**Comment by kwagyeman** [comment]
Send a PR for the fix of you've found it.

**Comment by iabdalkader** [comment]
Thanks!
