### ISSUE TITLE
Binary ops bug when using BMP

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv#534]
### Steps to reproduce
1. Create a 320x240 black filled BMP and save as mask.bmp
2. Copy the image to SD card and run the following script:
```
import sensor, image
sensor.reset()
sensor.set_pixformat(sensor.GRAYSCALE)
sensor.set_framesize(sensor.QVGA)
sensor.skip_frames(time=1000)
while(True):
   sensor.snapshot().b_and("mask.bmp")
```

### Expected behaviour
The framebuffer should be all black/clear. It works as expected with pgm.

### Actual behaviour
Garbage output black/white dots. This was reported on the forums too http://forums.openmv.io/viewtopic.php?f=6&t=1356

### Describe your setup

**IDE version:**
2.2.0
**Firmware version:**
3.4.1/2
**Operating system:**
Linux
### For developers

**GCC version:**
7.3.1 7-2018-q2-update
**Build target:**
OPENMV3/4

**Comment by iabdalkader** [comment]
@kwagyeman

**Comment by kwagyeman** [comment]
Will fix.
