### ISSUE TITLE
Python standart libraries

### ISSUE THREAD

**Issue by Duiesel** [openmv/openmv#54]
Hello Ibrahim!
I'm searching the libraries that You have been used in examples (in **face_tracking.py**)

``` python
import sensor, time, image
```

As I know **time** - is the internal Python library, but others - no.  :( 

Can You help me: where can I find them?

Thank You very much!
Best Regards, 
Alan

**Comment by iabdalkader** [comment]
Do you need the API documentation or modules code ?

**Comment by Duiesel** [comment]
Hello, Ibrahim!
I need modules code: can't find it in the repo.

Documentation is good too, but isn't necessary.

**Comment by iabdalkader** [comment]
https://github.com/openmv/openmv/tree/master/src/omv/py

**Comment by Duiesel** [comment]
I'm sorry does it mean that importing in OpenMV IDE working with not only .py files?

**Comment by AlexisTM** [comment]
http://docs.openmv.io/library/omv.sensor.html

What you were looking for was this, the documentation.

**Comment by iabdalkader** [comment]
@Duiesel Sorry I must've missed your last comment. Yes you can import .py files but sensor, image and time are all builtin modules (embedded in the firmware). Note the time module is not exactly the same standard Python time module, it's best to always check the docs linked by @AlexisTM.
