### ISSUE TITLE
Threshold arugment of get_histogram() doesn't adjust number of pixels sampled.

### ISSUE THREAD

**Issue by kwagyeman** [openmv/openmv#548]
Issues are here:

https://github.com/openmv/openmv/blob/master/src/omv/img/stats.c#L178
https://github.com/openmv/openmv/blob/master/src/omv/img/stats.c#L217
https://github.com/openmv/openmv/blob/master/src/omv/img/stats.c#L264

Change the code to compute the number of pixels before hand and then if in threshold mode count all pixels thresholded.

**Comment by iabdalkader** [comment]
@kwagyeman Can you fix this soon ?

**Comment by JCP13** [comment]
Hi,

I second that. I just made an order and I will need to use that feature when it arrives.  

Thank you in advance.

**Comment by kwagyeman** [comment]
Fixed in https://github.com/openmv/openmv/pull/655
