### ISSUE TITLE
V1 build is broken

### ISSUE THREAD

**Issue by rogerlucas** [openmv/openmv#55]
compile not found pincfg.h file and exit with error.

arm-none-eabi-gcc -O2 -ggdb3 -DNDEBUG -std=gnu99 -Wall -Werror -mlittle-endian -mthumb -nostartfiles -mabi=aapcs-linux -fdata-sections -ffunction-sections -fsingle-precision-constant -Wdouble-promotion -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DARM_MATH_CM4 -D__FPU_PRESENT=1 -D__FPU_USED=1 -DUSE_USB_FS -DUSE_DEVICE_MODE -DUSE_USB_OTG_ID=0 -DHSE_VALUE=12000000 -DOPENMV1 -DSTM32F407xx -I. -Iinclude -I/root/test/src/cmsis/include/ -I/root/test/src/cmsis/include/st -I/root/test/src/sthal/include/ -I/root/test/src/fatfs/include/ -I/root/test/src/build/micropython/ -I/root/test/src/micropython/ -I/root/test/src/micropython/py/ -I/root/test/src/micropython/lib/mp-readline -I/root/test/src/micropython/stmhal/ -I/root/test/src/micropython/stmhal/usbdev/core/inc/ -I/root/test/src/micropython/stmhal/usbdev/class/inc/ -I/root/test/src/micropython/stmhal/boards/OPENMV1/ -I/root/test/src/omv/ -I/root/test/src/omv/py/ -I/root/test/src/omv/img/ -I/root/test/src/winc1500/include/ -c -o /root/test/src/build/omv/sdcard_spi.o sdcard_spi.c
sdcard_spi.c:33:20: fatal error: pincfg.h: No such file or directory
 #include "pincfg.h"
                    ^
compilation terminated.
make[1]: *** [/root/test/src/build/omv/sdcard_spi.o] Error 1
make[1]: Leaving directory `/root/test/src/omv'
make: *** [objs] Error 2

**Comment by kwagyeman** [comment]
Not relevant anymore.
