### ISSUE TITLE
deep_sleep.py example does not work with STM32H7 cam

### ISSUE THREAD

**Issue by pyresChris66** [openmv/openmv#573]
### Steps to reproduce
1. Connect STM32H7 cam to your computer
2. Run Openmv IDE with deep_sleep.py
3. Connect and execute

### Expected behaviour
Camera should restard around 30s

### Actual behaviour
Camera restarts immediately, or never restarts or works sometimes just once...

### Describe your setup
**IDE version: 2.2.0
**Firmware version:3.4.2
**Operating system: windows 10

**Comment by iabdalkader** [comment]
I just fixed this issue, try the latest firmware on github.
