### ISSUE TITLE
LED.intensity() doesn't dim the LED

### ISSUE THREAD

**Issue by deshipu** [openmv/openmv#58]
The documentation at https://openmv.io/docs/library/pyb.LED.html#pyb-led claims that we can pass a value to the ``LED.instensity()`` function, and that will set the brightness of the given LED. However, there is no difference in brightness between 1 and 255 -- all of them result in blindingly bright light, except for 0, which turns the LED off.

**Comment by iabdalkader** [comment]
The LEDs on OpenMV boards are not connected to timers, so dimming doesn't work.

**Comment by deshipu** [comment]
I that case I guess it's a documentation error.

**Comment by kwagyeman** [comment]
Will fix documentation issue.
