### ISSUE TITLE
how use python code read video, not use openide

### ISSUE THREAD

**Issue by zhanwen** [openmv/openmv#627]
### Steps to reproduce
1. I try use python opencv read video, but i fail, i only read mac camera, not read openmv video.
python code:
```
import cv2
# i try parameters use 0,1,2,3,4,5, but only 0 is available
video = cv2.VideoCapture(0)
test = video.isOpened()
# cv2.VideoCapture(0) output true, this is mac computer camera
# cv2.VideoCapture(1) output false
# cv2.VideoCapture(2) output false
print(test)
```
In OPENMV IDE, the camera is success, now i want use python read video, then show web pages. can this be done? What are some ways to use python read video? thanks.

**Comment by iabdalkader** [comment]
Pleas post your questions on the forums.
