### ISSUE TITLE
ValueError: Timer(4) is reserved on firmware 3.5.2

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#662]
When I run this script:
https://github.com/openmv/openmv/blob/master/scripts/examples/23-Motor-Shield/motor-shield-power-driver.py

IDE raise error: ValueError: Timer(4) is reserved

New firmware disables timer4.

**Comment by iabdalkader** [comment]
Yes timer 4 is reserved, use another timer.

**Comment by kwagyeman** [comment]
I think we need to change the example script then Ibrahim.

**Comment by iabdalkader** [comment]
I did that already when I reserved those timers.

**Comment by iabdalkader** [comment]
Right, will update the motor shield example as well.
