### ISSUE TITLE
Wrong i2c bus speed on CAM H7

### ISSUE THREAD

**Issue by garivetm** [openmv/openmv#676]
### Steps to reproduce
1. Initialize the i2c bus on a H7 CAM to 400 kHz :
````
from pyb import I2C

# Objects (I2C, INT_pin, VL53L0X)
i2c = I2C(2)
i2c.init(I2C.MASTER, baudrate=400000)
i2c.scan()
````
2. Run this code on an H7 cam with firmware v3.5.2.
3. Scope SCL line

### Expected behaviour
I2c bus speed should be the same as the one specified by the i2c constructor baudrate argument : 400 kHz

### Actual behaviour
The measured i2c bus speed is around 800 kHz.
By the way, 200kHz is not supported, why ?

### Describe your setup

**IDE version:**
v2.2.0
**Firmware version:**
v3.5.2

**Comment by iabdalkader** [comment]
Hi, I've tuned the I2C timings as best as I could, with these new settings I measured 100KHz, 400KHz and ~850-900KHz. Note the timings depend on the rise/fall times, so you may see different results with your board. To adjust the timings for your board you can bypass the frequency and set the timing directly with the timingr arg, for example:
```
i2c.init(I2C.MASTER, timingr=0xE0701F28)
```

> By the way, 200kHz is not supported, why ?
You can only set the I2C to standard, fast and fast plus mode (100KHz, 400KHz and 1000KHz respectively).

This fix will be in the next release.
