### ISSUE TITLE
OpenMV output Wav file

### ISSUE THREAD

**Issue by carlevan** [openmv/openmv#690]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Describe your setup

**IDE version:**

**Firmware version:**

**Operating system:**

### For developers

**GCC version:**

**Build target:**

**Comment by carlevan** [comment]
can anyone plss help me. i am creating a project in which when an openmv detects it will output a wav sound and the user will hear it via earphone or speaker

**Comment by iabdalkader** [comment]
@carlevan please fill out the issue template or at least put a link to the forums post.

**Comment by iabdalkader** [comment]
someone else already reported this.
