### ISSUE TITLE
CIF settings for OV7725 ?

### ISSUE THREAD

**Issue by labviewegypt** [openmv/openmv#694]
To get CIF images,is it settings we have to send it to the camera or its done over MCU itself ?

**Comment by kwagyeman** [comment]
Set the resolution to CIF.

**Comment by labviewegypt** [comment]
@kwagyeman 
Thank you for you reply
I want to clear more about my question , i am using my own board with stm32l496 mcu ,i just using openMV  ov7725 camera breakout over my PCB .
Also,i am using the drivers from openMV repository,Everything working fine with me.
I want to take snapshots with CIF resolution and i dont know how ?
My question is there any certain configurations i have to send it to the camera to get this CIF resolution ? or to get CIF images you have to get images in VGA resolution (for example) then do some operation on MCU to get CIF ?

**Comment by kwagyeman** [comment]
You do sensor.set_framesize(sensir.cif) in MicroPython. If you are trying to do this in C please lookup what the above MicroPython snippet does and mimic that in C. Please see the sensor_set_framesize() function.

Also, if you are using your own board we do not provide help support for that.
