### ISSUE TITLE
openmv2 status

### ISSUE THREAD

**Issue by rene-dev** [openmv/openmv#72]
Hi,
is the openmv2 board usable at the moment?
I could not find any source for the chip in a bga package, any suggestions?

Rene

**Comment by iabdalkader** [comment]
We're sourcing our chips directly from Omnivision.

**Comment by kwagyeman** [comment]
Unless you plan on buying 1500 at once we're going to be the only source for the cameras. We're ordering directly from the factory. Great thing about this is that they work when we get them.
