### ISSUE TITLE
PORTENTA with stm32h743_af.csv

### ISSUE THREAD

**Issue by Dieter-Graef** [openmv/openmv#733]
[stm32h747_af.zip](https://github.com/openmv/openmv/files/4261353/stm32h747_af.zip)

Hello,
I just noticed that you are working an the PORTENTA device but using the file stm32h743_af.csv for pin assignment. Therefor i want kindly point you to my Gihub project https://github.com/Dieter-Graef/Pinmaker that produces the af.csv files right from the STM32CubeMX database

. It requires a bit work after. Mainly resorting and renaming some pins. See the examples with a stm32h747_af.csv file that works fine.
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Describe your setup

**IDE version:**

**Firmware version:**

**Operating system:**

### For developers

**GCC version:**

**Build target:**

**Comment by kwagyeman** [comment]
What's the issue being fixed?

**Comment by Dieter-Graef** [comment]
LCD with DSI cant be used.

**Comment by iabdalkader** [comment]
Thank you for the AF file, there's no driver for DSI at this point anyway. Note the H747 support is not official yet, when it becomes supported and the AF is updated I'll be sure update ours.
