### ISSUE TITLE
OV5640 driver error

### ISSUE THREAD

**Issue by kidswong999** [openmv/openmv#746]
firmware version: 3.6.0
code:
```
import sensor, time, image

# Reset sensor
sensor.reset()
sensor.set_contrast(3)
sensor.set_gainceiling(16)
sensor.set_framesize(sensor.VGA)
sensor.set_windowing((320, 240))
sensor.set_pixformat(sensor.GRAYSCALE)
```

assert:
ValueError: Failed to set framesize!
when sensor.set_framesize(sensor.VGA)

OV5640 assert error, but OV7725 is OK. I think OV5640 driver has an issue.

<img width="362" alt="截屏2020-03-30下午1 28 48" src="https://user-images.githubusercontent.com/9582040/77878208-64c66b80-728a-11ea-99bb-d8090a07d9c6.png">

**Comment by kwagyeman** [comment]
Initialize in the reverse order. The issue happens because the format isn't set yet and I have strict checks. Will fix.

**Comment by kwagyeman** [comment]
This is fixed.
