### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by Kevincoooool** [openmv/openmv#757]
When I compile the openmv/src in ubuntu,i got this error:
CC ../../extmod/vfs_fat_file.c
CC ../../extmod/vfs_lfs.c
CC ../../extmod/utime_mphal.c
CC ../../extmod/uos_dupterm.c
CC ../../lib/embed/abort_.c
CC ../../lib/utils/printf.c
MPY /home/kevin/openmv/src/../scripts/libraries/vec/distance.py
make[1]: ../../mpy-cross/mpy-cross: Command not found
../../py/mkrules.mk:129: recipe for target '/home/kevin/openmv/src/build/micropython/frozen_mpy/vec/distance.mpy' failed
make[1]: *** [/home/kevin/openmv/src/build/micropython/frozen_mpy/vec/distance.mpy] Error 127
Makefile:584: recipe for target 'FIRMWARE_OBJS' failed
make: *** [FIRMWARE_OBJS] Error 2

**Comment by iabdalkader** [comment]
You need to rebuild mpy-cross...
```cd src/micropython/mpy-cross && make```

**Comment by Kevincoooool** [comment]
Thanks!
