### ISSUE TITLE
Image.mean() corrupts memory

### ISSUE THREAD

**Issue by matsondawson** [openmv/openmv#764]
### Steps to reproduce
1. Run this script:

```python
import sensor, image, time, pyb

sensor.reset()
sensor.set_pixformat(sensor.GRAYSCALE) # or GRAYSCALE...
sensor.set_framesize(sensor.QQVGA) # or QQVGA...
sensor.skip_frames(time = 2000)
clock = time.clock()

# the color palette is actually an image, this allows you to use image ops to create palettes
# the image must have 256 entries i.e. 256x1, 64x4, 16x16 and have the format rgb565
palette = image.Image(256,1, sensor.RGB565)
palette.mean(32)

while(True):
    clock.tick()

    img = sensor.snapshot()

    print(clock.fps())
```
### Expected behaviour
Image gets averaged over 32 pixel window.

### Actual behaviour
Hardware hangs or resets.

### Describe your setup

**IDE version:** 
2.4.0

**Firmware version:** 
MicroPython v1.12-omv OpenMV v3.6.1 2020-03-30; OPENMV4-STM32H743

**Operating system:**
Windows 10 Home

**Comment by kwagyeman** [comment]
It shouldn't even run.

**Comment by kwagyeman** [comment]
Think you can send a PR to fix this? I'm working on an interface library right now. Code for mean is here:

https://github.com/openmv/openmv/blob/master/src/omv/img/filter.c#L134

**Comment by kwagyeman** [comment]
Mmm, the issue is that the image is smaller than the kernel. The current code doesn't handle this at all right now.

**Comment by matsondawson** [comment]
Ah good, shouldn't be too hard to fix.  Should I raise an error in py_mean or return if the image is too small? or both?

**Comment by kwagyeman** [comment]
You couldn't that would be the easy method to prevent use of it. Yo'll have to modify a lot of things in the current method to work with an image of that size. But, I think it's doable. The inner kernel loop samples from the right pixels... but, when I go to copy it back it blows up.

**Comment by kwagyeman** [comment]
Actually, looking more closely, the current code should basically handle this. There's probably a slight assumption somewhere.

**Comment by matsondawson** [comment]
Is it this at filter.c:254 ?

```c
            // Copy any remaining lines from the buffer image...
            for (int y = img->h - ksize, yy = img->h; y < yy; y++) { // !! y would start at 1-32 = -31
                memcpy(IMAGE_COMPUTE_GRAYSCALE_PIXEL_ROW_PTR(img, y), // !! this would compute a pointer before the image data
                       IMAGE_COMPUTE_GRAYSCALE_PIXEL_ROW_PTR(&buf, (y % brows)),
                       IMAGE_GRAYSCALE_LINE_LEN_BYTES(img));
            }
```

**Comment by kwagyeman** [comment]
Yeah, that's it. Actually, every filter method is affected by the same bug. This is the cleanup process at the end of the transfer.

I think you just need to do

for (int y = IM_MAX(img->h - ksize, 0), yy = img->h; y < yy; y++) {

**Comment by kwagyeman** [comment]
Note, passing 32 for the kernel size is not a 32 wide kernel, it's a 65 pixel wide kernel. Kernel size is 2k+1.

**Comment by kwagyeman** [comment]
Let me know if that works. If it does, then can you apply that fix for all places in the firmware using the same for () loop. You just need to search for

for (int y = img->h - ksize, yy = img->h; y < yy; y++) {

**Comment by matsondawson** [comment]
The fix works.

**Comment by kwagyeman** [comment]
K, please send a PR.
