### ISSUE TITLE
Adding custom AprilTag

### ISSUE THREAD

**Issue by KBacsa** [openmv/openmv#802]
I would like to add the detection of custom april tags as mentioned in #356 , mainly Tag36H8. 
### Steps to reproduce

1. Generated tags and codes using [apriltag-generation](https://github.com/AprilRobotics/apriltag-generation)

2. Create a new april tag family in apriltag.c such as :
```
////////////////////////////////////////////////////////////////////////////////////////////////////
//////// "tag36h8"
////////////////////////////////////////////////////////////////////////////////////////////////////

const apriltag_family_t tag36h8 = {
    .ncodes = 36042,
    .black_border = 1,
    .d = 6,
    .h = 8,
    .codes = {
       ...
      }
}
```

3. Add codes from Tag36h8.java file.

4. In imlib.h I added the mask constant such as :

```
typedef enum apriltag_families {
    TAG16H5 = 1,
    TAG25H7 = 2,
    TAG25H9 = 4,
    TAG36H10 = 8,
    TAG36H11 = 16,
    ARTOOLKIT = 64,
    TAG36H8 = 32
} __attribute__((aligned(8))) apriltag_families_t;
```

5. Enable family in python code.

### Expected behaviour
The AprilTag should be detectable.

### Actual behaviour
The AprilTag is not detected. Interestingly, if ```.h = 12```, the tags can be detected but with the wrong ID, I'm not sure I understand how the hamming distance influences the detection.

### Describe your setup

**IDE version:**
Qt Creator 4.5.2

**Firmware version:**

**Operating system:**
Ubuntu 18.04.3

### For developers

**GCC version:**
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Build target:**
[Kendryte GNU toolchain for RISC-V](https://github.com/kendryte/kendryte-gnu-toolchain) (using MaixPy project)

**Comment by kwagyeman** [comment]
Please send a PR for integrating the new tag type. Given this is a highly technical feature addition just for you it shouldn't be to hard for you to add this to the code base.
