### ISSUE TITLE
HD plus has garbage on screen in HD and QHD with JPEG pixformat

### ISSUE THREAD

**Issue by matsondawson** [openmv/openmv#806]
### Steps to reproduce
1. Run standard helloyworld.py, with these settings
sensor.set_pixformat(sensor.JPEG)
sensor.set_framesize(sensor.HD)
![corrupted](https://user-images.githubusercontent.com/1276179/82511363-344fcf00-9b61-11ea-9451-580df4d2a360.jpg)

### Expected behaviour
Standard camera image rendered.

### Actual behaviour
Has camera image with some garbage pixels.

### Describe your setup

**IDE version:**
2.4.0

**Firmware version:**
Latest master build from git.

**Operating system:**
Windows 10

### For developers

**GCC version:**
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Build target:**
H7 Plus

**Comment by iabdalkader** [comment]
Can you test again after doing a git pull ? I've just merged 2 PRs with JPEG and OV5640 fixes.

**Comment by kwagyeman** [comment]
This has been fixed with the latest jpeg code fix.

**Comment by matsondawson** [comment]
Awesome. Closing.
