### ISSUE TITLE
vflip ov7725 with V3.6.4 firm on M7

### ISSUE THREAD

**Issue by pyresChris66** [openmv/openmv#813]
### Steps to reproduce
1. sensor.vflip(True) with ov7725

### Expected behaviour
vertical rotated image

### Actual behaviour
vertical rotated image with different colors

### Describe your setup
**IDE version:**
V2.4.0
**Firmware version:**
V3.6.4
**Operating system:**
windows 10

### For developers
**GCC version:**
7.5.0
**Build target:**
OPENMV3

**Comment by kwagyeman** [comment]
What imaging mode are you using?

**Comment by pyresChris66** [comment]
RGB565, VGA

**Comment by kwagyeman** [comment]
Ah, yeah, then it's bayer. The issue is that the readout window shifted by 1 pixel messing up the bayer image data.

RGB565, VGA doesn't fit on the H7 regular so we silently convert to BAYER.

**Comment by kwagyeman** [comment]
Will fix.

**Comment by kwagyeman** [comment]
Fixed: https://github.com/openmv/openmv/pull/819
