### ISSUE TITLE
Move memset to init0()

### ISSUE THREAD

**Issue by iabdalkader** [openmv/openmv#839]
@kwagyeman init() is only called once, so sensor_t is zero'd once, I think we can move this to init0() where it belongs :

https://github.com/openmv/openmv/blob/22c03559ef8360d732253290863f1b8159fea5b7/src/omv/sensor.c#L289

Noticed it while doing something else.

**Comment by kwagyeman** [comment]
This was not a bug. You just broke the firmware with this.
