### ISSUE TITLE
some commit from v3.6.7 to 91dac4c break OpemMV3 camera

### ISSUE THREAD

**Issue by DeqingSun** [openmv/openmv#885]
### Steps to reproduce
1. check out master and compile, upload.
2. camera error -2
3. but when checkout to v3.6.7 and recompile and upload, the camera works just fine. The dfu files in releases worked as expected.

**Comment by iabdalkader** [comment]
I think this issue has been fixed. @DeqingSun Can you pull and try again ?

**Comment by DeqingSun** [comment]
@iabdalkader Great! it works. Thanks.
