### ISSUE TITLE
find_rects() printout for overlapping rectangles

### ISSUE THREAD

**Issue by timhenderson17** [openmv/openmv#888]
### Steps to reproduce
1. Use find_rects() function (with threshold 8000 but have had issue with multiple thresholds)
2. Point camera at an area with many rectangles

### Expected behaviour
Nothing should be printed

### Actual behaviour
When (I'm assumig) overlapping rectangles are detected it prints: "uh oh, no preference for overlappingdetection"

^The space is missing between overlapping and detection in the message

### Describe your setup
Using the H7, with OV7725, RGB565, QQVGA

**IDE version:**
2.5.1

**Firmware version:**
3.6.4

**Operating system:**
Windows

**Comment by kwagyeman** [comment]
From here: https://github.com/openmv/openmv/blob/master/src/omv/img/apriltag.c#L11884

**Comment by kwagyeman** [comment]
https://github.com/openmv/openmv/pull/1095
