### ISSUE TITLE
Using https for git in Firmware Guide?

### ISSUE THREAD

**Issue by DeqingSun** [openmv/openmv#896]
Now the tutorial is using SSH to clone git repos. And there will be "Permission denied (publickey)." error if it is not set.
Maybe it is worthwhile to change those public repos to https to avoid those issue?

**Comment by iabdalkader** [comment]
Which tutorial ? It should be https

**Comment by kwagyeman** [comment]
Everything is https now days. Google will lower your search rankings if you don’t use https. We are also required to having everything be https per our cyber insurance policy.
