### ISSUE TITLE
sensor.set_auto_whitebal(False)

### ISSUE THREAD

**Issue by redcrow** [openmv/openmv#902]
### Steps to reproduce
1. call sensor module function set_auto_whitebal
2. sensor.set_auto_whitebal(False)
3. ValueError: Sensor control failed!

### Expected behaviour
sensor.set_auto_whitebal(False) should disable

### Actual behaviour
Error kicks out  ==> ValueError: Sensor control failed!

### Describe your setup

**IDE version:**
2.6.0
**Firmware version:**
3.6.7
**Operating system:**
WIN 10
### For developers

**GCC version:**

**Build target:**

**Comment by redcrow** [comment]
Using the MT9V034 sensor

**Comment by kwagyeman** [comment]
It's a grayscale sensor. There's no white balance.
