### ISSUE TITLE
How to create a hidden py module

### ISSUE THREAD

**Issue by Kevincoooool** [openmv/openmv#912]
### Steps to reproduce
1.How to create a hidden py module and put it in the file system so that other py can call this hidden file when running
2.I have written a py program, but I don’t want others to see my program, I just want them to call it
3.

### Expected behaviour
I found that there is a line of code in main.c to run boot.py. At that time, I did not find where the content of the boot.py file was generated. If I put my py file in this hidden boot.py file, Can I power on and run my program?

### Actual behaviour
// Run boot script(s)
    if (first_soft_reset) {
        // Execute the boot.py script before initializing the USB dev to
        // override the USB mode if required, otherwise VCP+MSC is used.
        exec_boot_script("/boot.py", false, false);
        // Execute the selftests.py script before the filesystem is mounted
        // to avoid corrupting the filesystem when selftests.py is removed.
        exec_boot_script("/selftest.py", true, false);
    }

### Describe your setup

**IDE version:**

**Firmware version:**

**Operating system:**

### For developers

**GCC version:**

**Build target:**

**Comment by kwagyeman** [comment]
Hi, just put your script in the scripts/libraries folder, it will be compiled into the firmware as a frozen module. Then just call that script in main.py.

The code will be compiled as byte code as not viewable at that point in the firmware. Someone can still read out the firmware however. But, it will not easily be viewable.

**Comment by Kevincoooool** [comment]
Thank you！！！！！
