### ISSUE TITLE
Trouble using cascade_convert.py

### ISSUE THREAD

**Issue by marko19a** [openmv/openmv#929]
I'm trying to convert this file: [ball_cascade.zip](https://github.com/openmv/openmv/files/5410054/ball_cascade.zip)
I got it from http://profs.scienze.univr.it/~bloisi/tutorial/balldetection.html

## Error i get on python3.8 and 2.7:
Converting new XML format..
Traceback (most recent call last):
  File "cascade_convert.py", line 426, in <module>
    main()
  File "cascade_convert.py", line 423, in main
    cascade_binary_universal(args.file, args.stages, args.name)
  File "cascade_convert.py", line 104, in cascade_binary_universal
    cascade_binary(path, n_stages, name)
  File "cascade_convert.py", line 173, in cascade_binary
    fout.write(struct.pack('h', int(float(t.childNodes[0].nodeValue.split()[3])*4096))) #int16_t
struct.error: short format requires SHRT_MIN <= number <= SHRT_MAX

## OS: pop_os 20.04

**Comment by iabdalkader** [comment]
```
<stageType>BOOST</stageType>
<featureType>LBP</featureType>
```
This looks like a different type of cascade, which is not supported. This script is really basic and only supports Haar Cascades (old and new formats).
