### ISSUE TITLE
VCP readline throws

### ISSUE THREAD

**Issue by icm0** [openmv/openmv#934]
### Steps to reproduce
1. Setup a USB_VCP() object
2. Save script to board, and reset. Leave IDE disconnected
3. Call readlines() or readline()

### Expected behavior
A line should be read
### Actual behavior
An exception is thrown

### Describe your setup

**IDE version:**
2.6.5
**Firmware version:**
3.6.8
**Operating system:**
Ubuntu 18.04
### For developers

**GCC version:**

**Build target:**

**Comment by iabdalkader** [comment]
Hi, I did some testing and it's Not actually a bug, the issue is in that script you posted on the forums:

```python
cmd = usb.readlines(timeout=50) #fails here
```

Unlike `send` and `recv`,   `readline` and `readlines` functions don't take any args so that line raises an exception.

Here's a simple test script save it as main.py:

```python
import time
from pyb import USB_VCP

usb = USB_VCP()

while(True):
    time.sleep(20)
    if usb.any():
        lines = usb.readlines()
        for line in lines:
            usb.send(line)
```

And on the PC using Python3:

```python
#!/usr/bin/python
import sys, serial, struct, time
port = '/dev/ttyACM1'
sp = serial.Serial(port, baudrate=115200, bytesize=serial.EIGHTBITS, parity=serial.PARITY_NONE,
            xonxoff=False, rtscts=False, stopbits=serial.STOPBITS_ONE, timeout=None, dsrdtr=True)
sp.setDTR(True) # dsrdtr is ignored on Windows.
while (True):
    sp.write("HelloWorld!\n".encode())
    sp.flush()
    print(sp.readline().decode(), end="")
    time.sleep(0.100)
```
Output:

```
HelloWorld!
HelloWorld!
HelloWorld!
HelloWorld!
HelloWorld!
HelloWorld!
```
