### ISSUE TITLE
compiler warning in 64bit cpu

### ISSUE THREAD

**Issue by heyuanjie87** [openmv/openmv#980]
STATIC mp_obj_t py_image_get_pixel(uint n_args, const mp_obj_t *args, mp_map_t *kw_args)
{
    //...
}
STATIC MP_DEFINE_CONST_FUN_OBJ_KW(py_image_get_pixel_obj, 2, py_image_get_pixel);
//py/obj.h
typedef mp_obj_t (*mp_fun_var_t)(size_t n, const mp_obj_t *);
---------------------------------------------------
 i port this project to k210(riscv-64),in 64bit cpu "uint" is different from "size_t".
this causes a lot of compilation warnings,hope to fix this problem in a future release.

**Comment by kwagyeman** [comment]
You should send the error to MicroPython folks. That's not something we will fix directly. The issue resides in the py/obj.h file which is in MicroPython.
